/**
 * Editorial concept lexicon for the News relevance index. Each row names a durable syllabus concept and the
 * spellings news feeds use for it; build-relevance.mjs derives every PYQ count mechanically, so nothing here
 * asserts exam demand. Rows without CSE/UPPCS/taxonomy support are published as unbacked context, not signals.
 *
 * Row: tier | subject | topic | concept |alias; alias; ... [| flags]
 *   tier 3  a named institution, law, scheme, treaty, species, mission or place: enough to carry an article
 *   tier 2  a syllabus theme: needs one more piece of evidence
 *   tier 1  a broad or ambiguous word: supporting evidence only
 *   ^ALIAS  matched case-sensitively (short acronyms that are also ordinary words)
 *   flags   g = meaningful worldwide; d = an Indian institution whose name other countries also use
 */
const table = `
3|Economy|Banking and monetary policy|RBI|Reserve Bank of India; RBI; Reserve Bank; RBI governor; central bank of India
2|Economy|Banking and monetary policy|Monetary policy|monetary policy; repo rate; reverse repo; cash reserve ratio; statutory liquidity ratio; monetary policy committee; MPC; rate hike; rate cut; policy rate; liquidity framework; open market operations; standing deposit facility
2|Economy|Banking and monetary policy|Banking regulation|banking regulation; banking regulations; Basel III; banking system; non performing assets; NPAs; bad loans; bank recapitalisation; public sector banks; NBFC; NBFCs; shadow banks; deposit insurance; Insolvency and Bankruptcy Code; IBC; NCLT; microfinance; payments banks; small finance banks; credit growth
3|Economy|Financial regulation|SEBI|Securities and Exchange Board of India; SEBI
2|Economy|Financial regulation|Financial markets regulation|IRDAI; PFRDA; insider trading; sovereign gold bond; government securities; G secs; bond market; municipal bonds; green bonds; credit rating agencies; sovereign rating; bond yields; treasury yields; retail traders; retail investors; derivatives; F&O
2|Economy|Prices and growth|Inflation|inflation; consumer price index; CPI; wholesale price index; WPI; food inflation; core inflation; retail inflation; deflation; stagflation
2|Economy|Prices and growth|GDP and growth|GDP; gross domestic product; GVA; economic growth; growth forecast; growth rate; national income; per capita income; double deflation; recession; economic slowdown; index of industrial production; IIP; PMI; purchasing managers index; core sector; Indian economy; India's economy; domestic demand; consumption demand; demand problem; economy
3|Economy|Taxation|GST|goods and services tax; GST; GST Council; input tax credit
2|Economy|Taxation|Taxation|income tax; corporate tax; direct taxes; indirect taxes; tax base; tax buoyancy; tax evasion; tax havens; CBDT; CBIC; customs duty; excise duty; cess; surcharge; capital gains tax; windfall tax; tax devolution; tax reform; tax reforms; angel tax; equalisation levy
2|Economy|Public finance|Fiscal policy|fiscal policy; fiscal deficit; revenue deficit; primary deficit; government budget; union budget; state budget; FRBM; public debt; government borrowing; capex; capital expenditure; government expenditure; disinvestment; fiscal consolidation; off budget borrowings; state finances; fiscal federalism; public expenditure; subsidies; subsidy
3|Economy|Fiscal federalism|Finance Commission|Finance Commission; 16th Finance Commission; 15th Finance Commission
3|Economy|Development policy|NITI Aayog|NITI Aayog
2|Economy|Employment|Employment and labour|unemployment; unemployment rate; labour code; labour codes; labor code; demographic dividend; periodic labour force survey; PLFS; labour force participation; gig workers; gig economy; informal sector; informal workers; minimum wage; minimum wages; job creation; jobless growth; migrant workers; skill development; EPFO; social security code; labour reforms; jobs; creating jobs; employment; hiring slowdown; wage ceiling; wage growth; layoffs
2|Economy|External sector|Balance of payments and currency|current account deficit; balance of payments; forex reserves; foreign exchange reserves; exchange rate; rupee depreciation; rupee; remittances; capital account; external debt; foreign portfolio investors; FPI; FPIs; currency swap; internationalisation of the rupee; dollar index; de dollarisation
2|Economy|External sector|Trade policy|trade deal; trade agreement; free trade agreement; FTA; FTAs; bilateral trade; trade deficit; tariff; tariffs; reciprocal tariffs; export; exports; imports; export curbs; export ban; anti dumping duty; anti dumping; non tariff barriers; rules of origin; trade war; most favoured nation; trade policy; foreign trade policy; bilateral investment treaty; safeguard duty; countervailing duty|g
3|International relations|International trade|WTO|World Trade Organization; World Trade Organisation; WTO; dispute settlement body|g
2|Economy|Investment|Investment and industry|FDI; foreign direct investment; production linked incentive; PLI scheme; PLI; Make in India; industrial policy; industrial corridor; special economic zone; SEZ; SEZs; MSME; MSMEs; startups; startup ecosystem; ease of doing business; manufacturing sector; industrial output; industrial production; manufacturing output; private investment; capital formation; public private partnership; PPP model; competition commission; CCI; anti competitive
2|Economy|Infrastructure|Infrastructure|infrastructure investment; national infrastructure pipeline; Gati Shakti; PM Gati Shakti; dedicated freight corridor; national highways; NHAI; Bharatmala; Sagarmala; inland waterways; major ports; high speed rail; Vande Bharat; metro rail; UDAN; civil aviation; DGCA; logistics policy; smart cities; AMRUT; urban infrastructure; expressway; airport privatisation; major ports; port infrastructure; port project; highway; highways; tolling; toll; multi lane free flow
2|Economy|Energy|Energy security|energy security; crude oil; oil prices; oil imports; strategic petroleum reserve; strategic petroleum reserves; natural gas; LNG; city gas distribution; piped natural gas; PNG; gas pricing; OPEC; OPEC+; ethanol blending; ethanol; biofuels; coal; coal production; coal imports; power sector; discoms; electricity act; power grid; nuclear power; nuclear energy; small modular reactor; small modular reactors; petroleum; fuel prices; energy transition; critical minerals; rare earth; rare earths; rare earth magnets; lithium; PNGRB; power transmission; transmission lines; oil markets; oil market; global oil; oil pipeline; pipeline; jet fuel; gas price|g
2|Environment|Energy transition|Renewable energy|renewable energy; solar power; solar energy; wind power; offshore wind; green hydrogen; green energy; green energy corridor; battery storage; energy storage; pumped storage; compressed biogas; CBG; rooftop solar; PM Surya Ghar; International Solar Alliance; clean energy; electric vehicles; EVs; EV policy; FAME; CAFE norms; fuel efficiency norms; biogas; hydropower; hydel; ^CAFE; CAFE III|g
2|Economy|Agriculture|Agriculture|minimum support price; MSP; crop insurance; PM Fasal Bima; food security; public distribution system; PDS; agricultural policy; soil health; agriculture; farmers; farm sector; kharif; rabi; procurement; paddy procurement; fertiliser; fertilisers; fertilizer; urea; irrigation; agricultural marketing; APMC; e NAM; farm laws; farm income; crop diversification; horticulture; foodgrain; foodgrains; buffer stock; FCI; sugarcane; FRP; pulses; oilseeds; edible oils; millets; natural farming; organic farming; PM Kisan; Kisan Credit Card; agricultural exports; fisheries; blue revolution; dairy; livestock; land reforms; cropping patterns; food processing; cold storage; cold storages; agri; sugar; sugar mills; sugar output; paddy; wheat; rice exports; farm
2|Economy|Agriculture|Monsoon and rainfall|monsoon; southwest monsoon; northeast monsoon; rainfall deficit; India Meteorological Department; IMD; El Nino; La Nina; Indian Ocean Dipole; drought; heatwave; heat wave; heatwaves; cyclone; cyclones; cloudburst; western disturbance; Doppler weather radar; weather radar; weather radars; rain deficit; rainfall
2|Economy|Digital economy|Digital payments and public infrastructure|UPI; unified payments interface; digital payments; digital public infrastructure; DPI; Aadhaar; DigiLocker; ONDC; account aggregator; central bank digital currency; CBDC; e rupee; digital rupee; cryptocurrency; crypto assets; virtual digital assets; fintech; financial inclusion; Jan Dhan; direct benefit transfer; DBT; NPCI
2|Economy|International institutions|IMF and World Bank|International Monetary Fund; IMF; World Bank; special drawing rights; SDR; Asian Development Bank; ADB; New Development Bank; AIIB; World Economic Outlook; Bretton Woods|g
2|Economy|Reports and development|Reports and indices|human development index; human development report; global hunger index; multidimensional poverty; multidimensional poverty index; economic survey; world happiness report; global gender gap; gender gap report; ease of living; SDG index; Gini coefficient; poverty line; poverty estimates; household consumption expenditure survey; census; caste census; NFHS; national family health survey; World Inequality Report; global innovation index; logistics performance index; NSO; national sample survey|g
2|Economy|Global economy|Global economy|Federal Reserve; US Fed; ^Fed; European Central Bank; ECB; global recession; global growth; sanctions; supply chain; supply chains; global supply chains; friend shoring; oil shock; debt crisis; sovereign debt; global trade; protectionism; deglobalisation; dollar dominance; G7 price cap; price cap|g

3|Polity|Constitution and rights|Constitution|constitution of India; Indian Constitution; the Constitution; constitutional; fundamental rights; basic structure; fundamental duties; directive principles; preamble; constitutional amendment; constitution amendment; constitutional morality; constitutional validity; unconstitutional; Constituent Assembly; right to privacy; right to life; freedom of speech; freedom of expression; right to equality; Ninth Schedule|d
3|Polity|Constitution and rights|Constitutional articles|Article 14; Article 19; Article 21; Article 32; Article 226; Article 356; Article 370; Article 142; Article 143; Article 200; Article 239AA; Article 371; Article 371A; Article 44; Article 25; Article 16; Article 15; Article 311; Article 368
1|Polity|Constitution and judiciary|Supreme Court|Supreme Court; ^SC; apex court; top court; constitution bench; constitutional bench; Chief Justice of India; CJI; collegium|d
1|Polity|Constitution and judiciary|High Courts|High Court; high courts; ^HC|d
2|Polity|Constitution and judiciary|Judicial system|judicial review; judicial independence; judicial appointments; judicial activism; judicial overreach; pendency; pending cases; tribunals; tribunal; National Green Tribunal; NGT; Lok Adalat; legal aid; contempt of court; public interest litigation; PIL; curative petition; review petition; all India judicial service; judicial reforms; e courts; live streaming of court; judicial accountability; impeachment of judge; in house inquiry; arbitration; mediation; Gram Nyayalaya; bail reform; undertrials; death penalty; capital punishment; sedition; preventive detention; UAPA; PMLA; Bharatiya Nyaya Sanhita; BNS; BNSS; criminal laws; personality rights; e challans; e challan
2|Polity|Federalism|Federalism|federalism; federal structure; centre state relations; Centre state; cooperative federalism; competitive federalism; governor's assent; President's Rule; Inter State Council; inter state water dispute; river water dispute; Cauvery; Krishna water; delimitation; statehood; Union Territory; Union Territories; special category status; Sixth Schedule; Fifth Schedule; autonomous district council; autonomous council; asymmetric federalism; three language policy; three language formula; language policy; concurrent list; state list; Sarkaria; Punchhi; Governor's assent; Raj Bhavan; Governor withholds; Governor vs; federal balance; federal
3|Polity|Constitutional bodies|Election Commission|Election Commission of India; Election Commission; ECI; ^EC; Chief Election Commissioner; ^CEC; election commissioners; poll panel; special intensive revision; ^SIR; electoral roll; electoral rolls; voter list; voter lists; voter roll; voter rolls|d
2|Polity|Elections|Electoral reforms|electoral reforms; electoral bonds; simultaneous elections; one nation one election; model code of conduct; EVM; EVMs; VVPAT; Representation of the People Act; RPA 1951; anti defection; anti defection law; Tenth Schedule; political funding; election funding; NOTA; delimitation commission; reservation for women; women's reservation; universal adult franchise; disqualification of MLAs; disqualification of MPs; political parties; inner party democracy; voter turnout; remote voting; postal ballot; Rajya Sabha elections; by election
3|Polity|Constitutional bodies|CAG|Comptroller and Auditor General; CAG; CAG report|d
2|Polity|Constitutional bodies|Constitutional and statutory bodies|Union Public Service Commission; state public service commission; Attorney General; Lokpal; Lokayukta; Central Vigilance Commission; CVC; Central Information Commission; CIC; National Human Rights Commission; NHRC; National Commission for Women; NCW; National Commission for Scheduled Castes; National Commission for Scheduled Tribes; NCBC; NCPCR; Law Commission; Enforcement Directorate; CBI; Central Bureau of Investigation; NIA; National Investigation Agency; Delimitation Commission; Pay Commission; 8th Pay Commission; Competition Commission of India; TRAI; CCPA; FSSAI; CDSCO; NPPA; NMC; UGC; AICTE; NTA; Central Pollution Control Board; CPCB
2|Polity|Parliament|Parliament and legislation|Parliament; Lok Sabha; Rajya Sabha; parliamentary committee; parliamentary committees; parliamentary panel; standing committee; select committee; joint parliamentary committee; JPC; Public Accounts Committee; ordinance; money bill; private member's bill; question hour; zero hour; no confidence motion; parliamentary privilege; winter session; monsoon session; budget session; legislative council; state legislature; legislative assembly; assembly passes; passes bill; introduces bill; amendment bill; Uniform Civil Code; UCC; Waqf; Citizenship Amendment Act; CAA; NRC; women's reservation bill; office of profit; Council of Ministers; Union Cabinet; Cabinet approves; Cabinet nod; Lok Sabha Speaker; Assembly Speaker|d
2|Polity|Local government|Local self-government|Panchayati Raj; panchayat; panchayats; gram sabha; gram panchayat; urban local bodies; municipal corporation; municipal corporations; municipalities; 73rd amendment; 74th amendment; state finance commission; PESA; devolution; local bodies; ward committees
2|Governance|Welfare and government policy|Government schemes|government scheme; government schemes; centrally sponsored scheme; centrally sponsored schemes; central sector scheme; PM KISAN; Ayushman Bharat; PM JAY; PMJAY; MGNREGA; MGNREGS; VB G RAM G; Jal Jeevan Mission; Swachh Bharat; PM Awas Yojana; PMAY; Ujjwala; PM Poshan; mid day meal; Poshan Abhiyaan; ICDS; anganwadi; anganwadis; National Health Mission; Samagra Shiksha; PM SHRI; Mission Karmayogi; Atal Pension Yojana; PM Vishwakarma; PM SVANidhi; Lakhpati Didi; Stand Up India; Mudra; Smart Cities Mission; Viksit Bharat; aspirational districts; aspirational blocks; One District One Product; ODOP; National Education Policy; NEP 2020; ^NEP; welfare scheme; welfare schemes; free bus travel; cash transfer; cash transfers; freebies; housing scheme; pension scheme; old pension scheme; unified pension scheme; social audit; PM CARES; free travel; housing programme; PM Internship Scheme; internship scheme; LPG; eKYC; flagship scheme
2|Governance|Accountability|Governance and accountability|right to information; RTI; RTI Act; civil service; civil services; civil servants; bureaucracy; IAS officers; lateral entry; public accountability; good governance; e governance; citizen charter; whistleblower; corruption; anti corruption; Prevention of Corruption Act; administrative reforms; police reforms; prison reforms; FCRA; foreign contribution regulation; NGOs; civil society; self help groups; SHGs; cooperatives; digital governance; grievance redressal; public service delivery; regulatory reform; deregulation; decriminalisation; compliance burden; Jan Vishwas; cooperative societies; regulatory framework; light touch regulation; consumer protection; online shopping; e commerce rules; regulators; citizen interaction; UPSC turns 100
2|Governance|Health|Public health|public health; universal health coverage; health insurance; primary health care; out of pocket expenditure; National Health Policy; drug pricing; generic medicines; essential medicines; medical devices; drug regulator; drug recall; spurious drugs; antimicrobial resistance; AMR; tuberculosis; ^TB; malaria; dengue; Nipah; HIV; ^AIDS; non communicable diseases; cancer screening; lung cancer; maternal mortality; infant mortality; malnutrition; stunting; anaemia; anemia; sickle cell; vaccination; vaccine; vaccines; immunisation; universal immunisation programme; pandemic; pandemic treaty; epidemic; plague; outbreak; zoonotic; One Health; mental health; tobacco control; food safety; food adulteration; contraceptive; fertility rate; total fertility rate; population policy; ageing population; medical education; ICMR; AIIMS; AYUSH; telemedicine; digital health mission; rare diseases; organ donation; surrogacy; assisted reproductive; drug batches; drug batch; recalls; cancer drug; cancer; energy drink; institutional deliveries; institutional delivery; suicide risk; older adults|g
3|International relations|International institutions|WHO|World Health Organization; World Health Organisation; ^WHO|g
2|Governance|Education|Education policy|education policy; higher education; school education; learning outcomes; ASER; foundational literacy; dropout rate; dropout rates; gross enrolment ratio; Right to Education; RTE Act; universities; foreign universities; university rankings; NIRF; research funding; Anusandhan National Research Foundation; ANRF; exam paper leak; paper leak; coaching centres; NEET; CUET; mother tongue instruction; school dropouts; teacher vacancies; skilling
2|Governance|Social justice|Social justice and vulnerable sections|social justice; reservation; reservations; quota; creamy layer; sub classification; Scheduled Castes; Scheduled Tribes; ^SCs; ^STs; ^OBC; ^OBCs; other backward classes; EWS quota; tribal rights; forest rights; Forest Rights Act; community forest rights; particularly vulnerable tribal groups; PVTG; PVTGs; manual scavenging; bonded labour; child labour; child marriage; POCSO; domestic violence; dowry; gender justice; gender equality; women's empowerment; women's safety; women in workforce; female labour force participation; transgender persons; persons with disabilities; disability rights; senior citizens; elderly; street vendors; homeless; slum; slums; minorities; minority rights; caste discrimination; caste based; untouchability; human rights; vulnerable sections; juvenile justice; maternity benefit; sexual harassment at workplace; POSH Act; marital rape; same sex marriage; live in relationships; internal migration; urbanisation; poverty; inequality; hunger; nutrition; unsafe public spaces; safety of women; women safety; free bus; migrants; ration card; small loans; disability pension; veterans
1|Governance|Society|Society and social change|regionalism; communalism; secularism; globalisation; social media regulation; population growth; demographic transition; diaspora; Indian diaspora; brain drain; migration; refugees; refugee; tribal communities; caste system; joint family; urban poor; middle class

3|Environment|Wetlands and conservation|Ramsar Convention|Ramsar; Ramsar site; Ramsar sites; wetland conservation; wetlands; wetland; mangroves; mangrove|g
2|Environment|Biodiversity and conservation|Protected areas|protected area; protected areas; national park; national parks; tiger reserve; tiger reserves; wildlife sanctuary; wildlife sanctuaries; biosphere reserve; biosphere reserves; eco sensitive zone; eco sensitive zones; ecologically sensitive area; ^ESA; elephant corridor; elephant corridors; conservation reserve; marine protected area; marine protected areas; Western Ghats; Sundarbans; Aravalli; Aravallis; Kaziranga; Corbett; Kuno; Buxa; Great Nicobar; Gir forest; Gir national park|g
2|Environment|Biodiversity and conservation|Biodiversity and wildlife|biodiversity; endangered species; critically endangered; invasive species; IUCN; Red List; ^CITES; Convention on Biological Diversity; Kunming Montreal; Wildlife Protection Act; Project Tiger; Project Elephant; Project Cheetah; cheetah reintroduction; tiger reintroduction; tigress; tiger census; elephant census; great Indian bustard; snow leopard; Asiatic lion; one horned rhino; gharial; Gangetic dolphin; vultures; pangolin; human wildlife conflict; human elephant conflict; wildlife conservation; wildlife trade; poaching; habitat loss; coral reef; coral reefs; coral bleaching; Great Barrier Reef; deforestation; afforestation; forest cover; India State of Forest Report; forest fires; wildfires; species discovered; new species; extinction; rewilding; translocation; captive breeding; migratory birds; flyway; seagrass; keystone species; orangutan; forest; forests; trees; elephants; elephant; primates|g
2|Environment|Climate and treaties|Climate change|climate change; global warming; climate treaty; Paris Agreement; UNFCCC; COP30; COP31; COP32; climate summit; UN climate summit; carbon emissions; greenhouse gas; greenhouse gases; emissions; net zero; carbon neutral; carbon neutrality; nationally determined contributions; NDC; NDCs; climate finance; loss and damage; carbon market; carbon markets; carbon credit; carbon credits; carbon tax; carbon pricing; CBAM; carbon border adjustment; methane; IPCC; sea level rise; glacial lake outburst; GLOF; glacial lakes; glacier; glaciers; glacial melt; permafrost; Arctic; Antarctica; Antarctic; ice sheet; climate adaptation; climate resilience; climate risk; climate justice; just transition; carbon capture; carbon sink; ocean acidification; climate damage; fossil fuels; fossil fuel; coal phase out; 1.5 degree|g
2|Environment|Environmental regulation|Pollution and environmental regulation|environmental impact assessment; EIA; environment protection act; environmental clearance; forest conservation; Forest Conservation Act; Van Adhiniyam; pollution control; air pollution; air quality; AQI; GRAP; graded response action plan; stubble burning; PM2.5; particulate matter; vehicular emissions; BS VI; green crackers; water pollution; river pollution; Ganga rejuvenation; Namami Gange; Yamuna; groundwater; groundwater depletion; water crisis; water scarcity; plastic waste; single use plastic; microplastics; solid waste; liquid waste; e waste; extended producer responsibility; landfill; landfills; leachate; sewage; sewage treatment; hazardous waste; biomedical waste; noise pollution; light pollution; sand mining; illegal mining; coal mine; coal mining; coastal regulation zone; CRZ; compensatory afforestation; CAMPA; environment ministry; MoEFCC; ozone; Montreal Protocol; Stockholm Convention; Minamata; forever chemicals; PFAS; pesticide; pesticides; oil spill; circular economy; waste management; green tribunal; PUC; pollution under control; plastics; mountain waste|g
2|Environment|Disaster management|Disaster management|disaster management; NDMA; NDRF; SDRF; disaster risk reduction; Sendai Framework; early warning; early warning system; flood; floods; flash floods; urban flooding; landslide; landslides; earthquake; earthquakes; tsunami; cyclone warning; drought relief; heat action plan; forest fire; avalanche; land subsidence; dam safety; Disaster Management Act; disaster relief; evacuation; vulnerability mapping; glacial lake|g
2|Geography|Physical geography|Physical geography|tectonic plates; plate tectonics; ocean currents; volcanic eruption; volcano; seismic zone; Himalayas; Himalayan; Indo Gangetic plain; Deccan; river basin; river linking; interlinking of rivers; Ken Betwa; Brahmaputra; Ganga; Indus; Teesta; Godavari; Narmada; delta; estuary; coastal erosion; river erosion; soil erosion; desertification; land degradation; aquifer; typhoon; hurricane; jet stream; polar vortex; ^ENSO; Andaman and Nicobar; Lakshadweep; small rivers; river rejuvenation; cartography; ocean research; research vessel; oceans; warmer oceans; ocean heat; marine heatwave|g
2|Geography|Resources|Resources and mapping|mineral resources; mineral auction; mining lease; deep sea mining; seabed mining; polymetallic nodules; water resources; freshwater resources; river water sharing; dam; dams; hydropower project; hydel project; national waterway; shale gas; gas hydrates; exclusive economic zone; continental shelf; census towns; geospatial; survey of India; minerals; mines; mining

3|Sci-Tech|Space technology|ISRO|ISRO; Indian Space Research Organisation; Chandrayaan; Gaganyaan; Aditya L1; Mangalyaan; NavIC; PSLV; GSLV; SSLV; NISAR; Bharatiya Antariksh Station; IN SPACe; NewSpace India; Sriharikota; Venus Orbiter; Shukrayaan
2|Sci-Tech|Space and science|Space exploration|space mission; lunar mission; Mars mission; space telescope; James Webb; gravitational waves; exoplanet; exoplanets; black hole; black holes; space station; International Space Station; astronaut; astronauts; satellite; satellites; satellite launch; launch vehicle; reusable rocket; payload; payloads; space debris; space situational awareness; Artemis; Artemis Accords; NASA; European Space Agency; asteroid; comet; solar storm; solar flare; dark matter; dark energy; neutrino; spacecraft; space economy; space policy; private space sector; SpaceX; Starlink; satellite internet; satcom; lunar exploration; moon mission; microgravity; gravity assist; Jupiter; Saturn; Hubble; supernova; neutron star; LIGO; Space Race; Sputnik; lunar; space telescope launch; Falcon 9; Falcon Heavy|g
2|Sci-Tech|Biotechnology|Biotechnology and health science|biotechnology; gene editing; CRISPR; genome sequencing; genome; genomic; genetic engineering; genetically modified; GM crops; GM mustard; Bt cotton; stem cell; stem cells; mRNA; monoclonal antibodies; gene therapy; CAR T; biosimilars; synthetic biology; bioeconomy; BioE3; DNA; RNA; cloning; xenotransplantation; antibiotic; antibiotics; superbug; superbugs; virus strain; pathogen; clinical trial; clinical trials; Nobel Prize in Medicine; Nobel Prize in Physiology; brain organoid; organoids; biofortification; nanotechnology; biomarkers; brain tissue; organoid; transplanted|g
2|Sci-Tech|Technology and regulation|Emerging technology and regulation|artificial intelligence; ^AI; generative AI; AI regulation; AI safety; AI agents; AI governance; IndiaAI; machine learning; large language model; large language models; deepfake; deepfakes; semiconductor; semiconductors; chip manufacturing; India Semiconductor Mission; quantum computing; quantum; quantum key distribution; QKD; National Quantum Mission; cybersecurity; cyber security; cyber attack; cyber attacks; cybercrime; cyber fraud; ransomware; data breach; data protection; data protection act; Digital Personal Data Protection; DPDP; data localisation; IT Rules; IT Act; intermediary liability; online gaming regulation; social media regulation; encryption; 5G; 6G; spectrum; telecom; Telecommunications Act; blockchain; internet shutdown; internet shutdowns; drones; drone; robotics; supercomputer; supercomputers; PARAM; data centre; data centres; data centers; cloud computing; digital sovereignty; facial recognition; surveillance; Pegasus; spyware; net neutrality; AI copyright; deep tech; deep technology; internet governance; 3D printing; internet of things; critical and emerging technologies; iCET; technology transfer|g
2|Sci-Tech|Science policy|Science, research and innovation|Nobel Prize; Nobel Prize in Physics; Nobel Prize in Chemistry; CSIR; DRDO; BARC; Department of Atomic Energy; nuclear reactor; fast breeder reactor; thorium; nuclear fusion; fusion reactor; ITER; superconductivity; superconductor; hydrogen fuel cell; fuel cell; research and development; R&D; patents; patent; intellectual property; IPR; scientific research; science policy; indigenous technology; indigenisation; Vigyan; LIGO India; particle accelerator; CERN; Large Hadron Collider; Higgs; atomic clock; lithium ion; sodium ion; solid state battery; desalination; green steel|g

3|International relations|International institutions|United Nations|United Nations; UN Security Council; UNSC; UN General Assembly; UNGA; UN Human Rights Council; UNHRC; ^UN; International Court of Justice; ICJ; International Criminal Court; ICC warrant; UNESCO; UNICEF; UNEP; UNDP; FAO; World Food Programme; ILO; UNCTAD; IAEA; UN peacekeeping; peacekeepers; UN charter; UNSC reform; permanent seat; veto|g
2|International relations|Treaties and agreements|Treaties and conventions|international treaty; international treaties; nuclear treaty; non proliferation treaty; NPT; CTBT; New START; UNCLOS; Indus Waters Treaty; Ganga water treaty; extradition treaty; mutual legal assistance; double taxation avoidance; Vienna Convention; Geneva Convention; Geneva Conventions; high seas treaty; BBNJ; plastics treaty; Outer Space Treaty; Chemical Weapons Convention; Biological Weapons Convention; Arms Trade Treaty; Wassenaar; Nuclear Suppliers Group; NSG; MTCR; Australia Group; civil nuclear deal; 123 agreement; international law; maritime boundary; ceasefire agreement; peace deal; peace agreement; peace talks; ceasefire; MoU signed; signs MoU; bilateral agreement; defence pact; security pact|g
2|International relations|Groupings|Multilateral groupings|G20; ^G7; BRICS; Quad; SCO; Shanghai Cooperation Organisation; ASEAN; East Asia Summit; BIMSTEC; SAARC; IORA; I2U2; AUKUS; NATO; African Union; Gulf Cooperation Council; GCC; OIC; Arab League; Commonwealth; Global South; Non Aligned Movement; IPEF; Indo Pacific Economic Framework; RCEP; CPTPP; IMEC; India Middle East Europe Economic Corridor; Belt and Road; BRI; CPEC; Chabahar; INSTC; International North South Transport Corridor; Financial Action Task Force; FATF; Interpol; OECD; Eurasian Economic Union; EFTA; Mercosur; Colombo Security Conclave; Mekong Ganga; minilateral; multilateralism|g
2|International relations|India and neighbourhood|India's neighbourhood|Pakistan; Bangladesh; Nepal; Bhutan; Sri Lanka; Maldives; Myanmar; Afghanistan; Taliban; Line of Control; LoC; Line of Actual Control; LAC; India China; India Pakistan; Indo Pak; Sino Indian; border talks; border dispute; Doklam; Galwan; Arunachal Pradesh; Aksai Chin; Kartarpur; Katchatheevu; Teesta water; Rohingya; neighbourhood first; Act East; SAARC summit; cross border terrorism; Indus waters; Dhaka; Kathmandu; Colombo; Thimphu; Kabul; Islamabad; South Asia|g
2|International relations|Bilateral and global|India's foreign policy|foreign policy; External Affairs Minister; Jaishankar; Ministry of External Affairs; MEA; foreign secretary; strategic autonomy; strategic partnership; bilateral ties; bilateral talks; bilateral relations; state visit; summit talks; India US; Indo US; India Russia; India EU; India UK; India Japan; India France; India Australia; India Germany; India UAE; India Israel; India Iran; India Saudi; India Africa; India ASEAN; India Canada; H 1B; visa policy; diaspora outreach; envoy; envoys; ambassador; high commissioner; diplomatic; diplomacy; summons envoy; summon envoys; Indo Pacific; Link West; Look East; soft power; vaccine diplomacy; defence cooperation; 2+2 dialogue; trade talks; India's proposal; visa; visas; visa bond; multi alignment; strategic multi engagement; ceremonial welcome
1|International relations|World affairs|United States|United States; ^US; U S; Washington; Trump; White House; Pentagon; US Congress; American|g
1|International relations|World affairs|China|China; Chinese; Beijing; Xi Jinping; Taiwan; Taiwan Strait; Tibet; Xinjiang; Hong Kong|g
1|International relations|World affairs|Russia and Ukraine|Ukraine; Russia; Russian; Putin; Kyiv; Moscow; Kremlin; Zelenskyy; Zelensky|g
1|International relations|World affairs|West Asia|Iran; Tehran; Iranian; Israel; Israeli; Gaza; Palestine; Palestinian; West Bank; Hamas; Hezbollah; Houthi; Houthis; Yemen; Syria; Iraq; Saudi Arabia; UAE; Qatar; Turkey; West Asia; Middle East; Gulf countries; Persian Gulf; Lebanon; Oman; Kuwait; Egypt|g
1|International relations|World affairs|Europe|Europe; European; European Union; ^EU; Germany; France; Britain; United Kingdom; ^UK; Italy; Spain; Poland; Brussels; Armenia; Azerbaijan|g
1|International relations|World affairs|East and Southeast Asia|Japan; South Korea; North Korea; Pyongyang; Seoul; Tokyo; Indonesia; Vietnam; Philippines; Singapore; Malaysia; Thailand; Cambodia; Australia|g
1|International relations|World affairs|Africa, Central Asia and the Americas|Central Asia; Kazakhstan; Uzbekistan; Africa; Sudan; Sahel; Ethiopia; Nigeria; Kenya; South Africa; Mauritius; Seychelles; Brazil; Canada; Mexico; Venezuela; Latin America; Arctic Council|g
3|Geography|Strategic geography|Maritime chokepoints and seas|Strait of Hormuz; Strait of Malacca; Red Sea; Suez Canal; Bab el Mandeb; Panama Canal; South China Sea; chokepoint; chokepoints; Arabian Sea; Bay of Bengal; Indian Ocean; Indian Ocean Region; Malacca; Hormuz; sea lanes|g
2|International relations|World affairs|Geopolitics and conflict|war; invasion; military offensive; airstrike; airstrikes; missile strike; missile strikes; blockade; naval blockade; nuclear talks; nuclear deal; nuclear programme; nuclear program; nuclear weapons; nuclear test; enrichment; uranium enrichment; troop deployment; troops; peace plan; truce; hostages; annexation; occupied territories; humanitarian crisis; humanitarian aid; famine; war crimes; genocide; coup; military junta; regime change; arms race; arms control; hypersonic; ballistic missile; ballistic missiles; aircraft carrier; great power; multipolar; world order; rules based order; regional order; proxy war; oil blockade; energy crisis; shipping lanes; freedom of navigation; territorial dispute; territorial waters; troop withdrawal; withdrawal of troops; pullout; militia; militias; leaving Iraq; Great Game; nuclear; nuclear gambit|g

2|Security|Defence|Defence and armed forces|defence; Indian Army; Indian Navy; Indian Air Force; ^IAF; armed forces; Chief of Defence Staff; CDS; theatre command; theatre commands; theaterisation; Agnipath; Agniveer; defence procurement; Defence Acquisition Council; defence exports; defence indigenisation; fighter jet; fighter jets; Tejas; Rafale; AMCA; fifth generation; BrahMos; Agni; Prithvi; Akash; S 400; submarine; submarines; INS; aircraft carrier Vikrant; warship; warships; missile test; missile defence; joint exercise; military exercise; Malabar exercise; defence startups; iDEX; HAL; defence corridor; defence budget; military modernisation; nuclear triad; nuclear doctrine; no first use; maritime security; maritime domain awareness; Coast Guard; anti submarine; drone warfare; air defence; integrated air defence; space command; cyber command; jet deal; jets; fighter aircraft; combat aircraft; Air Chief; Army Chief; Navy Chief; Navy sailor; naval
2|Security|Internal security|Internal security|internal security; terrorism; terrorist; terror attack; counter terrorism; insurgency; insurgent; insurgents; left wing extremism; LWE; Naxal; Naxals; Naxalism; Maoist; Maoists; militancy; militants; AFSPA; border management; border security; BSF; CRPF; CAPF; CAPFs; ITBP; Assam Rifles; border fencing; infiltration; illegal immigration; illegal migrants; detention centre; detention centres; drug trafficking; narco terrorism; narcotics; NDPS; money laundering; terror financing; hawala; organised crime; radicalisation; espionage; honey trapped; Official Secrets Act; national security; National Security Act; NSA; intelligence agencies; R&AW; Intelligence Bureau; NATGRID; coastal security; Manipur violence; ethnic violence; communal violence; riots; mob lynching; fake currency; human trafficking; arms smuggling; non state actors; lone wolf; hijack; hijacking; aviation security; crowd management; drug seizure; drug haul; heroin; paramilitary; CISF|g

2|History & Culture|Heritage and culture|Heritage and culture|world heritage; World Heritage Site; UNESCO tentative list; tentative list; intangible cultural heritage; archaeological survey; Archaeological Survey of India; ASI; GI tag; geographical indication; archaeological; archaeology; excavation; excavations; Harappan; Indus Valley; Keeladi; Rakhigarhi; inscription; inscriptions; classical language; classical languages; Sahitya Akademi; Jnanpith; Bharat Ratna; Padma awards; temple architecture; rock cut; Buddhist; Buddhism; Sufi; Bhakti; tribal art; handloom; handicrafts; folk art; folk dance; classical dance; Hindustani music; Carnatic; manuscripts; Gyan Bharatam; repatriation of antiquities; antiquities; Swadesh Darshan; PRASHAD; heritage site; heritage status; monument; monuments; Chola; Mauryan; Gupta period; Vijayanagara; Mughal; Ashokan; Sangam; megalithic; rock art; Sanskrit; Pali; Prakrit; Kumbh
2|History & Culture|Modern history|Modern Indian history|freedom struggle; freedom movement; national movement; Mahatma Gandhi; Gandhian; Nehru; Sardar Patel; Ambedkar; Subhas Chandra Bose; Bhagat Singh; Lal Bahadur Shastri; Tagore; Savarkar; Quit India; Non Cooperation; Civil Disobedience; Dandi; Jallianwala; 1857; Constituent Assembly debates; reorganisation of states; Green Revolution; Bhoodan; integration of princely states; Macaulay; colonial; socio religious reform; Swadeshi; Indian National Congress history; birth anniversary; death anniversary; Jayanti; Partition of India; Gandhi Jayanti; the Emergency

2|Governance|Uttar Pradesh|Uttar Pradesh governance|Uttar Pradesh; ^UP; UP government; UP govt; UP cabinet; Yogi Adityanath; UP CM; UP assembly; UP Vidhan Sabha; UPPSC; UP police; UPSIDA; UPEIDA; Lucknow; Kanpur; Varanasi; Kashi; Prayagraj; Allahabad High Court; Ayodhya; Gorakhpur; Noida; Greater Noida; Ghaziabad; Agra; Meerut; Mathura; Jhansi; Bareilly; Aligarh; Moradabad; Saharanpur; Bundelkhand; Purvanchal; Purvanchal Expressway; Ganga Expressway; Bundelkhand Expressway; Jewar airport; Noida International Airport; UP defence corridor; ODOP Uttar Pradesh; UP budget; UP GSDP; one trillion dollar economy; Mission Shakti; Kanya Sumangala; Mukhyamantri; Global Investors Summit; UP investors summit; ground breaking ceremony; Dudhwa; Pilibhit; Sonbhadra; Chitrakoot; Terai; Awadh; Rohilkhand; Braj; Maha Kumbh; Kashi Vishwanath; Ram Mandir; UP madrasa; sugarcane dues; UP Rajya Sabha
`

const TIERS = new Set(['1', '2', '3'])
/** @returns {{concept:string,aliases:{text:string,exact:boolean}[],subject:string,topic:string,tier:1|2|3,scope:'india'|'global'|'domestic'}[]} */
export function lexicon() {
  const rows = [], seen = new Set()
  for (const line of table.split('\n').map(l => l.trim()).filter(Boolean)) {
    const [tier, subject, topic, concept, spellings, flags = ''] = line.split('|').map(s => s.trim())
    if (!TIERS.has(tier) || !subject ||!topic|| !concept || !spellings) throw Error('Malformed lexicon row: ' + line.slice(0, 60))
    if (seen.has(concept)) throw Error('Duplicate concept: ' + concept)
    seen.add(concept)
    const aliases = [...new Set(spellings.split(';').map(s => s.trim()).filter(Boolean))].map(s => s.startsWith('^') ? { text: s.slice(1), exact: true } : { text: s, exact: false })
    rows.push({ concept, aliases, subject, topic, tier: Number(tier), scope: flags.includes('d') ? 'domestic' : flags.includes('g') ? 'global' : 'india' })
  }
  return rows
}
