/**
 * Editorial value: what a UPSC reader gains from an article, weighed from its headline and feed summary.
 * A syllabus topic is necessary and never sufficient: the article must also report a development, and its value
 * falls when it is party politics, case-level litigation, a State's day-to-day business, another country's
 * domestic affairs, a company's or a consumer's concern, or somebody's remark. Every point is listed with its reason.
 * Publisher volume, PYQ frequency and article bodies are absent.
 */
import { NOISE, type NoiseCategory } from '../evidence-lexicon.ts'
import { PhraseMatcher, tokenize } from '../match.ts'
import { NEWS_SOURCES } from '../sources.ts'
import type { NewsItem } from '../types.ts'
import type { StageCDecision } from './contracts.ts'
import { PROPOSITIONS } from './lexicon.ts'
import { classifySubject, type Subject } from './subject.ts'

export const EDITORIAL_POLICY = {
  id: 'tars-editorial/1',
  /** Evidence an article needs to be offered at all; the list is never filled below it. */
  floor: 6.5,
  /** Subjects where a daily reader gains least from routine reports ask for more. */
  subjectFloor: { Polity: 7, Governance: 7 } as Partial<Record<Subject, number>>,
  /** Feeds that mostly carry filler or promoted copy start behind; desks that write for understanding start ahead. */
  sourcePrior: { 'toi-world': -2, 'toi-science': -1.5, 'ht-world': -1, 'tribune-business': -1, 'india-ndtv-latest': -1, 'hindu-science': 1, 'substack-people-policies-progress-pib-india': 1 } as Record<string, number>,
  /** Current affairs matter most where the syllabus is least static. */
  subjectPriority: { Environment: 1.5, 'Sci-Tech': 1.5, 'International relations': 1, Economy: 1, Geography: 0.5, Security: 0.5, 'History & Culture': 0.5, Polity: 0, Governance: 0 } as Record<Subject, number>,
} as const

export interface EditorialReason { label: string; points: number; text?: string }
export interface Editorial { policy: typeof EDITORIAL_POLICY.id; score: number; floor: number; accepted: boolean; subject: Subject | null; reasons: EditorialReason[]; excluded?: string }

interface Topic { subject: Subject; id: string; weight: 1 | 2 | 3; terms?: string; cased?: string }
const t = (subject: Subject, id: string, weight: 1 | 2 | 3, terms?: string, cased?: string): Topic => ({ subject, id, weight, terms, cased })
/**
 * Examinable objects by subject. Weight 3 is a named, factual object a Prelims question can be set on or a core
 * Mains theme; 2 a standard syllabus theme; 1 a broad word that only supports. `terms` ignore case; `cased` do not.
 */
export const TOPICS: readonly Topic[] = [
  // Environment: species, protected areas, pollution, climate, conventions and regulators.
  t('Environment', 'protected-areas', 3, String.raw`national parks?|tiger reserves?|wildlife sanctuar(?:y|ies)|bird sanctuar(?:y|ies)|biosphere reserves?|conservation reserves?|community reserves?|protected areas?|eco.sensitive (?:zones?|areas?)|elephant (?:corridors?|passages?|reserves?)|wildlife corridors?|ramsar|wetlands?|mangroves?|coral reefs?|sacred groves?|chilika|kaziranga|sundarbans?|western ghats|aravallis?|nilgiris?|silent valley|great nicobar|kuno|gir forest|corbett|loktak|wular|bharatpur|keoladeo|pulicat|bhitarkanika|simlipal|nagarhole|periyar|manas|dachigam|hemis|namdapha|pench|kanha|bandhavgarh|ranthambore|sariska|tadoba|galapagos|amazon (?:rainforest|basin)?|great barrier reef|congo basin`, 'ESA|ESZ'),
  t('Environment', 'species', 3, String.raw`new species|endangered|critically endangered|vulnerable species|extinct(?:ion)?|invasive (?:species|plants?|alien)|migratory birds?|winged guests|bird (?:census|species|count)|great indian bustards?|bustards?|vultures?|gharials?|snow leopards?|asiatic lions?|cheetahs?|red pandas?|pangolins?|dugongs?|olive ridley|gangetic dolphins?|river dolphins?|hornbills?|sarus cranes?|amur falcons?|flamingos?|giant tortoises?|sea turtles?|whale sharks?|horseshoe crabs?|rhinos?|rhinoceros|hoolock|lion.tailed|nilgiri tahr|sangai|hangul|pygmy hog|mahseer|hilsa|waterlily|pollinators?|keystone species|poaching|wildlife (?:trade|trafficking|crime|census|protection|board)|human.wildlife conflict|man.animal conflict|biodiversity|habitat (?:loss|fragmentation)|captive breeding|reintroduc\w+|translocat\w+|juvenile fish\w*|overfishing|fish (?:stocks?|deaths?|kill)|roadkill`),
  t('Environment', 'animals', 2, String.raw`tigers?|elephants?|leopards?|lions?|dolphins?|crocodiles?|tortoises?|turtles?|whales?|sharks?|corals?|orchids?|butterfl(?:y|ies)|amphibians?|frogs?|bats?|bees|parrots?|owls?|eagles?|cranes?|wildlife|forests?|trees|species|ecosystems?|ecolog\w+`),
  t('Environment', 'pollution', 3, String.raw`air (?:pollution|quality)|clean air|smog|haze|stubble burning|particulate matter|pm ?2\.5|microplastics?|plastic (?:pollution|waste|ban|treaty)|single.use plastics?|e.waste|solid waste|landfills?|sewage|effluents?|river pollution|toxic (?:waste|foam|air|smog)|forever chemicals|pesticides?|oil spills?|noise pollution|groundwater (?:depletion|contamination|extraction)|sand mining|illegal mining|ozone (?:layer|hole|pollution)|acid rain|eutrophication|algal blooms?`, 'AQI|GRAP|PFAS|CPCB|NGT'),
  t('Environment', 'climate', 3, String.raw`climate (?:change|crisis|action|targets?|policy|litigation|adaptation|mitigation|resilience|risks?|emergency|goals?|finance|summit|talks|justice|funds?)|global (?:warming|heating)|greenhouse gas(?:es)?|carbon (?:emissions?|markets?|tax|credits?|capture|budget|border|sinks?|trading|neutral\w*)|net.zero|emissions|methane|fossil.fuels?|coal phase.?(?:out|down)|energy transition|just transition|loss and damage|paris agreement|kyoto protocol|montreal protocol|sea.level rise|ice sheets?|glacial (?:melt|retreat)|permafrost|ocean (?:warming|acidification|heat)|marine heatwaves?|coral bleaching|tipping points?|deforestation|afforestation|forest (?:cover|fires?|rights|clearance|diversion|survey)|tropical forests?|rainforests?|wildfires?|desertification|land degradation|green (?:hydrogen|credits?|bonds?|cover|tribunal)|renewable (?:energy|capacity)|green energy|solar (?:power|capacity|energy|parks?)|wind (?:power|energy|farms?)|offshore wind|biofuels?|ethanol blending|environmental (?:clearance|impact assessment|regulation|law|governance|protection)`, String.raw`COP ?\d{2}|UNFCCC|IPCC|UNEP|IUCN|CITES|CBD|CAMPA|NTCA|EIA|NDCs?|CBAM|ISA|CAFE(?: III)?`),
  // Sci-Tech: space, frontier physics and computing, biotechnology and health science.
  t('Sci-Tech', 'space', 3, String.raw`gaganyaan|chandrayaan\S*|aditya.l1|mangalyaan|space (?:station|missions?|programme|program|policy|sector|debris|telescope|docking|economy)|launch vehicles?|reusable rockets?|rockets?|spacecraft|orbiters?|landers?|rovers?|lunar|moon mission|mars|asteroids?|comets?|exoplanets?|black holes?|galax(?:y|ies)|supernova\w*|neutron stars?|pulsars?|dark (?:matter|energy)|gravitational waves?|cosmic|astronom\w+|astrophysic\w+|astronauts?|human spaceflight|satellites?|satellite (?:internet|spectrum|communications?|broadband)|satcom|low.earth orbit|geostationary|telescopes?|solar (?:storms?|flares?|cycle)|bennu`, 'ISRO|NASA|ESA|JAXA|IN-SPACe|NSIL|NISAR|PSLV|GSLV|SSLV|LVM3|NavIC|JWST|Starlink|OneWeb|SpaceX|Artemis'),
  t('Sci-Tech', 'frontier', 3, String.raw`quantum.secure|quantum key|brain (?:tissue|organoids?|implants?)|space race|battery storage|quantum (?:computing|computers?|communication|technolog\w+|sensing|mission|link|dots?|encryption|supremacy)|nuclear (?:clocks?|fusion|reactors?|energy|power|liability)|atomic clocks?|fusion (?:reactor|energy)|small modular reactors?|thorium|fast breeder|superconduct\w+|semiconductors?|chip (?:manufacturing|fabs?|design)|particle (?:physics|accelerator|collider)|neutrinos?|higgs|antimatter|nanotechnolog\w+|graphene|photonics?|lasers?|solid.state batter(?:y|ies)|lithium.ion|sodium.ion|hydrogen fuel|fuel cells?|supercomput\w+|artificial intelligence|generative ai|large language models?|machine learning|deepfakes?|data cent(?:re|er)s?|blockchain|internet of things|robotics?|humanoid robots?|autonomous vehicles?|self.driving|facial recognition|brain.computer|neurotechnolog\w+|mind.reading|3d print\w+|additive manufacturing|hypersonic|directed energy|nobel prize in (?:physics|chemistry|medicine|physiology)|(?:physics|chemistry|medicine) nobel|millennium prize|mathematic\w+`, '6G|5G|AI|A\\.I\\.|LLMs?|AGI|CERN|LIGO|ITER|IndiaAI|MeitY|GPUs?'),
  t('Sci-Tech', 'bio-health', 3, String.raw`genomes?|genomic\w*|gene (?:editing|therapy|drive)|genetic\w*|crispr|dna|rna|mrna|stem cells?|vaccines?|antibod(?:y|ies)|virus(?:es)?|pathogens?|outbreaks?|epidemics?|pandemics?|plague|bird flu|avian influenza|nipah|mpox|zika|ebola|dengue|malaria|tuberculosis|cancer (?:therap(?:y|ies)|vaccines?|research)|antimicrobial resistance|superbugs?|antibiotics?|clinical trials?|biotechnolog\w+|bio.?manufacturing|gm crops?|genetically modified|gene.edited|synthetic biology|biosensors?|organoids?|xenotransplant\w+|rare diseases?|sickle cell|fossils?(?![ -]fuel)|dinosaurs?|pala?eontolog\w+|human evolution|evolved|hominins?|neanderthals?`, 'H5N1|HIV|AMR|TB|ICMR|CSIR|CAR-T'),
  t('Sci-Tech', 'research', 2, String.raw`scientists?|researchers?|physicists?|astronomers?|biologists?|study (?:finds|shows|reveals|suggests|links|points)|new study|research (?:finds|shows|reveals)|discover(?:y|ies|ed|s)?|breakthroughs?|world.s first|first.ever|indigenous(?:ly)? (?:developed|built)|innovation|r&d|research and development|science policy|technolog(?:y|ies)|drones?|spectrum|telecom|cyber\w*`),
  // International relations: India's external relations, the neighbourhood, groupings, conflicts with systemic effect.
  t('International relations', 'india-bilateral', 3, String.raw`india.(?:us|u\.s\.|china|russia|japan|eu|uk|france|germany|pakistan|bangladesh|nepal|bhutan|sri lanka|maldives|myanmar|afghanistan|iran|israel|saudi|uae|gulf|turkey|canada|australia|asean|africa|brazil|malaysia|indonesia|vietnam|singapore|korea|taiwan|central asia|estonia|italy|new zealand|oman|qatar|egypt)\b|indo.(?:us|pacific|pak|china|russian|japan|bangla|nepal|lanka|french|german)|bilateral (?:ties|talks|trade|relations|agreement|investment treaty)|strategic partnership|comprehensive (?:economic|strategic) partnership|free trade agreements?|trade (?:deal|pact|talks|agreement)|investment treat(?:y|ies)|extradition|indus waters treaty|line of actual control|border (?:talks|dispute|agreement|pact)|foreign policy|strategic autonomy|multi.alignment|non.alignment|neighbou?rhood (?:first|policy)|act east|look east|global south|indo.pacific|diaspora|indian(?:.origin| nationals| seafarers| workers| students)|visas?(?: (?:regime|rules|curbs|policy|crackdown|bond))?|ceasefire proposal|jet deal|green cards?|deportations?|migrant workers?|state visit|foreign (?:minister|secretary)|external affairs|ambassador|high commissioner|envoy|mango diplomacy|\w+ diplomacy`, 'MEA|FTA|CEPA|BIT|LAC|LoC|H-1B|H1-B|PERM|NRIs?|OCI|TIGA|AITIGA'),
  t('International relations', 'groupings', 3, String.raw`united nations|security council|general assembly|world trade organi[sz]ation|international court of justice|international criminal court|shanghai cooperation|european union|european parliament|african union|arab league|gulf cooperation council|commonwealth|arctic council|non.aligned movement|nobel peace prize|peace nobel|global governance|international order|rules.based order|multilateral\w*|multipolar\w*|world order|international law|un (?:reforms?|charter|peacekeeping)|mecca (?:pact|accord)|makkah accord|defen[cs]e pact|abraham accords`, String.raw`UNSC|UNGA|UNHRC|WTO|ICJ|ICC|IAEA|FATF|OPEC\+?|BRICS|G20|G7|G77|SCO|Quad|QUAD|ASEAN|SAARC|BIMSTEC|IORA|APEC|NATO|AUKUS|EU|CIS|GCC|AIIB|NDB|I2U2|IPEF|RCEP|NPT|UNCLOS`),
  t('International relations', 'conflict', 2, String.raw`ceasefire|truce|peace (?:talks|plan|process|deal|pact)|sanctions?|nuclear (?:talks|deal|programme|program|weapons?|arsenal|proliferation)|arms control|war crimes|genocide|great.power|geopolitic\w+|strait of hormuz|hormuz|red sea|suez canal|malacca|south china sea|taiwan strait|korean peninsula|west asia|middle east|gulf (?:security|states|war)|ukraine war|gaza|houthis?|taliban|rohingya|refugees?|coup|junta|trade war|export controls?|nord stream|belt and road|string of pearls|debt trap`),
  t('International relations', 'neighbourhood', 2, undefined, 'Pakistan|China|Chinese|Nepal|Bhutan|Bangladesh|Sri Lanka|Maldives|Myanmar|Afghanistan|Tibet|Iran|Russia|Japan|Taiwan'),
  // Economy: macro indicators, monetary and fiscal instruments, external sector, sectors and regulation.
  t('Economy', 'monetary', 3, String.raw`repo rate|reverse repo|cash reserve ratio|statutory liquidity|liquidity adjustment|standing deposit|monetary policy|monetary tightening|policy rate|rate (?:hike|cut)|interest rates?|inflation|consumer price|wholesale price|price stability|bond yields?|government (?:bonds?|securities|borrowing)|open market operations?|forex reserves?|foreign exchange reserves?|rupee (?:depreciat\w+|falls?|slides?|weakens|value|internationali[sz]ation)|exchange rate|currency swap|digital (?:rupee|currency|payments?)|central bank digital currency|merchant discount rate|non.performing assets?|bad loans?|bank (?:credit|deposits?|mergers?|recapitali[sz]ation|licen[cs]es?)|financial (?:inclusion|stability)|insolvency|priority sector|microfinance|credit growth|shadow banks?`, String.raw`RBI|MPC|CRR|SLR|LAF|MSF|SDF|CBDC|UPI|MDR|NPCI|NPAs?|NBFCs?|IBC|SEBI|IRDAI|PFRDA|NABARD|SIDBI|FCNR|ECB`),
  t('Economy', 'fiscal-growth', 3, String.raw`gross domestic product|economic growth|growth (?:forecast|outlook|estimate|rate|projection)|world economic growth|global (?:growth|economy|trade|recession)|fiscal (?:deficit|policy|consolidation|federalism|stimulus)|revenue deficit|public debt|sovereign (?:rating|debt)|credit rating|capital expenditure|capex|union budget|budget (?:estimates?|allocation)|tax (?:revenue|collections?|devolution|reforms?|buoyancy|benefit|exemption)|direct tax(?:es)?|income.tax (?:bill|act|slabs?|law)|gst (?:council|rates?|collections?|reforms?|rationali[sz]ation|compensation|slabs?)|goods and services tax|input tax credit|e.way bill|customs dut(?:y|ies)|subsid(?:y|ies)|disinvestment|privati[sz]ation|public sector (?:banks?|undertakings?|enterprises?)|finance commission|current account deficit|trade deficit|balance of payments|foreign direct investment|greenfield investments?|capital flows?|remittances|exports?|imports?|unemployment|jobless growth|creating jobs|demand problem|labou?r force|job creation|employment (?:data|rate)|wage growth|per capita income|poverty (?:line|rate|estimates?)|inequality|household (?:savings|consumption|debt)|consumption expenditure|industrial (?:production|output)|core sector|manufacturing (?:sector|output|pmi)|services (?:sector|pmi)|excess capacity|overcapacity|economic survey`, String.raw`GDP|GVA|CAD|GST|IGST|CGST|ITC|FDI|FPI|IIP|PMI|CPI|WPI|PLFS|NSO|NSSO|CBDT|CBIC|DPIIT|CEA|FRBM`),
  t('Economy', 'sectors', 2, String.raw`critical minerals?|rare earths?|supply chains?|tariffs?|energy security|oil (?:prices|supply|exports?|trade)|production.linked incentives?|make in india|semiconductor mission|msmes?|start.?ups?|global capability cent(?:re|er)s?|gig (?:economy|workers?)|e.commerce|agricultur\w+|farm (?:laws?|income|loan waiver|sector|exports?)|farmers?|minimum support prices?|rabi|kharif|crop (?:yields?|diversification|prices|insurance)|food (?:prices|inflation|processing|grain stocks?|security)|fertili[sz]ers?|horticulture|fisheries|dairy|rice exports?|wheat|pulses|oilseeds|edible oils?|sugar|cotton|tea prices|infrastructure|national highways?|railways?|electrification|freight|logistics|major ports|cargo traffic|shipbuilding|aviation|airports?|telecom|spectrum (?:auction|allocation|allotment)|power (?:sector|plants?|demand)|electricity|discoms?|coal (?:production|imports?|sector|supplies|stocks?)|thermal power|crude (?:oil)?|natural gas|strategic petroleum reserves?|ethanol|sustainable aviation fuel|electric (?:vehicles?|buses)|fuel efficiency|real estate|insurance|pension|maritime insurance|corporate governance|competition (?:law|commission)|antitrust|geographical indication|rural (?:economy|income|enterprises?)|cooperatives?|self.help groups?|labou?r codes?|minimum wages?`, String.raw`MSMEs?|SMEs?|PLI|GCCs?|MSP|PM-KUSUM|PM-KISAN|PMFBY|FCI|APMC|eNAM|NHAI|PNGRB|TRAI|CCI|EPFO|ESIC|SEZs?|ONDC|EVs?|E20|E85|SAF|LNG|LPG|ATF|GI`),
  // Polity: the Constitution, Parliament, the judiciary and elections as institutions, not their daily politics.
  t('Polity', 'constitution', 3, String.raw`constitution(?:al)?(?! club)|basic structure|fundamental (?:rights?|duties)|directive principles|right to (?:privacy|life|equality|education|information|protest|vote|dissent|health|be forgotten)|article \d{1,3}[a-z]?\b|section \d{1,3}[a-z]?\b|preventive detention|sedition|freedom of (?:speech|expression|religion|the press)|uniform civil code|reservations?|quota|creamy layer|sub.classification|places of worship act|citizenship|anti.conversion|waqf|official language|three.language|delimitation|anti.defection|tenth schedule|money bill|centre.state|federal\w*|inter.state (?:council|water|river|border)|sixth schedule|fifth schedule|statehood|simultaneous elections|one nation,? one election|ordinance|parliamentary (?:panel|committee|privileges?|standing committee)|joint parliamentary committee|private member|impeachment|governor.s (?:assent|powers?|role|discretion)|president.s (?:rule|assent|reference)|speaker.s (?:powers?|decision|ruling)|collegium|judicial (?:review|appointments?|overreach|accountability|reforms?|pendency|independence)|constitution bench|larger bench|contempt of court|tribunals?|lokpal|lokayukta|electoral (?:rolls?|bonds?|reforms?)|special intensive revision|model code of conduct|election (?:funding|commission(?:ers?)?)|representation of the people|voting rights?|census|caste (?:census|enumeration)|internet shutdowns?|right to protest|criminal (?:laws?|justice)|bharatiya (?:nyaya|nagarik|sakshya)|death penalty|capital punishment|custodial (?:deaths?|violence|torture)|undertrials?|bail (?:reforms?|jurisprudence)|live.stream\w+ of court|airports? (?:named|renamed)|renam\w+`, String.raw`UCC|CAA|NRC|UAPA|PMLA|NSA|AFSPA|BNSS|BNS|BSA|CrPC|IPC|RTI|PIL|SIR|EVMs?|VVPAT|NOTA|CEC|ECI|CAG|UPSC|JPC|CJI|NHRC|NCSC|NCST|NCBC|CIC`),
  // Governance: schemes, social-sector policy, regulators and delivery.
  t('Governance', 'social-policy', 3, String.raw`ayushman bharat|jal jeevan|swachh bharat|pm awas|ujjwala|poshan|mid.day meals?|anganwadis?|mission (?:shakti|karmayogi|vatsalya|indradhanush)|national (?:education|health|digital|data|ai|sports|youth|cooperative) policy|national education policy|new education policy|paper leaks?|entrance exams?|exam reforms?|learning outcomes?|school education|higher education|foundational literacy|dropout rates?|preschool|upper.secondary|gender gap|public health|health (?:insurance|coverage|expenditure|system|infrastructure|gaps?)|universal health|malnutrition|stunting|anaemia|maternal mortality|infant mortality|child deaths|fertility rate|life expectancy|drug (?:pricing|regulation|regulator|prices)|trade margins?|cancer drugs?|generic (?:drugs|medicines)|essential medicines|prescription drugs|pharma (?:freebies|marketing)|tobacco control|mental health|senior citizens|elderly|disabilit(?:y|ies)|scheduled (?:castes?|tribes?)|tribal (?:welfare|rights|students)|forest rights act|manual scavenging|child (?:labou?r|marriage|rights)|women.s (?:safety|reservation|empowerment)|sexual harassment (?:law|act)|unsafe public spaces|street vendors?|e.challans?|detention cent(?:re|er)s?|cancer screening|lung cancer|drug (?:batches|recall)|front.of.(?:the.)?pack|warning labels?|trafficking|social (?:audit|security|justice)|welfare schemes?|direct benefit transfers?|public distribution system|ration cards?|food security act|rural employment|employment guarantee|skill development|digital public infrastructure|e.governance|data protection|aadhaar|road (?:safety|crashes|accidents? data)|urban (?:planning|flooding|local bod\w+|governance)|smart cit(?:y|ies)|affordable housing|land (?:records|acquisition|reforms?)|panchayati raj|panchayats?|gram sabhas?|municipal (?:finances?|bonds?)|disaster management|civil services? reforms?|lateral entry|police reforms?|prison reforms?|regulat(?:or|ors|ory|ion)|stray dogs?|rabies|social media (?:rules|regulation|firms)|online (?:gaming|safety)|it rules`, String.raw`NEP|UGC|NEET(?:-UG)?|NTA|CBSE|ASER|NFHS|NPPA|CDSCO|FSSAI|PDS|MGNREGA|MGNREGS|NREGA|DBT|NFSA|SHGs?|NDMA|NITI Aayog|DPDP|PM-JAY|ABDM|NHM|ASHA|ICDS|POSH|POCSO|SC/ST`),
  t('Governance', 'named-scheme', 3, String.raw`pradhan mantri \w+|\w+ yojana|national mission (?:on|for) \w+|national \w+ (?:drive|mission|programme|portal|policy) ?\d?(?:\.\d)?`, String.raw`PM[- ][A-Z][\w-]+(?: \d\.0)?|[A-Z]\w+ (?:Mission|Yojana|Abhiyan)|Mission [A-Z]\w+`),
  // Geography: physical processes, hazards, water and resources.
  t('Geography', 'physical', 3, String.raw`el ni[ñn]o|la ni[ñn]a|indian ocean dipole|polar vortex|jet streams?|western disturbances?|monsoons?|north.east monsoon|south.west monsoon|rain(?:fall)? deficit|cyclon(?:e|es|ic)|hurricanes?|typhoons?|cloudbursts?|landslides?|earthquakes?|seismic\w*|tsunamis?|volcan(?:o|oes|ic)|glacial lakes?|glaciers?|flash floods?|floods?|flood risk|droughts?|heat ?waves?|cold waves?|ocean currents?|plate tectonics|river (?:systems?|basins?|linking|interlinking|erosion|water)|interlinking of rivers|dams?|canals?|aquifers?|watersheds?|deltas?|estuar(?:y|ies)|plateaus?|himalayas?|himalayan|permafrost|sea ice|arctic|antarctic\w*|time zones?|urbani[sz]ation|migration patterns?|demographic (?:dividend|transition|change)|population (?:growth|decline|ageing|aging|census)|mineral (?:reserves?|deposits?|exploration)|lithium (?:reserves?|deposits?)|natural hazards?|low.pressure|depression over|bay of bengal|arabian sea|indian ocean`, 'IMD|GLOF|ENSO|IOD|Ravi|Beas|Sutlej|Chenab|Jhelum|Indus|Ganga|Yamuna|Brahmaputra|Teesta|Godavari|Krishna|Cauvery|Kaveri|Narmada|Mahanadi|Ken-Betwa|Polavaram|Mullaperiyar|Siachen'),
  // Security: defence capability, internal security and its institutions.
  t('Security', 'defence', 3, String.raw`defen[cs]e (?:procurement|acquisition|exports?|budget|production|reforms?|indigeni[sz]ation|manufacturing|corridor|deal|technology)|theatre commands?|chief of defen[cs]e staff|air force|indian navy|indian army|agnipath|agniveers?|armed forces|fighter.jets?|\d+ jets|jet (?:deal|plan|shortage)|aircraft carriers?|submarines?|anti.submarine|warships?|stealth (?:ship|frigate|fighter)|frigates?|destroyers?|missile (?:tests?|systems?|defen[cs]e)|ballistic missiles?|cruise missiles?|air defen[cs]e|anti.tank|drone warfare|military (?:exercises?|moderni[sz]ation|reforms?|base)|joint exercises?|naval (?:exercise|base|power)|nuclear (?:doctrine|triad|deterrence|submarine)|counter.?terror\w*|cross.border terror\w*|terror (?:financing|funding)|left.wing extremism|maoists?|naxal\w*|insurgenc(?:y|ies)|internal security|coastal security|maritime security|border (?:infrastructure|security|fencing|management)|ceasefire violations?|cyber ?(?:security|attacks?|crime|fraud|warfare)|official secrets act|intelligence (?:reforms?|agencies)|character of warfare|narco.terror\w*|fake currency`, String.raw`DRDO|HAL|CDS|BSF|CRPF|ITBP|CAPFs?|NSG|NIA|IAF|INS [A-Z]\w+|BrahMos|Agni-?\w*|Prithvi|Tejas|Rafale|S-400|Akash|Pralay|Arihant|Op(?:eration)? Sindoor|ATGMs?|UAVs?|MALE`),
  // History & Culture: archaeology, heritage, art forms, thinkers and awards.
  t('History & Culture', 'heritage', 3, String.raw`archaeolog\w+|excavat\w+|inscriptions?|harappan?|indus valley|megalith\w*|keeladi|rakhigarhi|world heritage|intangible (?:cultural )?heritage|heritage (?:sites?|buildings?|conservation|tag|city)|classical language|gi tags?|temple architecture|buddhist (?:art|sites?|relics|circuit)|manuscripts?|constituent assembly|freedom (?:struggle|movement|fighters?)|bhakti|sufi|vedic|upanishad\w*|chola|pallava|vijayanagara|mughal|mauryan?|gupta (?:era|period|empire)|tipu sultan|tribal (?:art|culture|heritage|uprising)|folk (?:art|dance|music)|classical (?:dance|music)|social reformers?|ayyankali|ambedkar|phule|mahatma gandhi|gandhiji?|nehru|shastri|sardar patel|subhas|bhagat singh|tagore|vivekananda|literature nobel|nobel (?:prize )?(?:in |for )?literature|jnanpith|sahitya akademi|booker|art and culture|ancient town|pitru paksha`, 'ASI|INTACH|UNESCO World Heritage'),
]

/** A reported development, with what it is worth in the headline. `explain` is a format, counted apart from these. */
const DEVELOPMENTS: readonly [string, RegExp, number][] = [
  ['law or policy action', new RegExp(PROPOSITIONS.law + String.raw`|\b(?:caps?|capped|impos(?:es|ed)|finali[sz]\w+|kicks in|comes? into (?:force|effect)|to come into effect|joins?|renamed?|named after|stockpil\w+)\b`, 'i'), 2], ['court decision', new RegExp(PROPOSITIONS.court, 'i'), 2],
  ['report, data or finding', new RegExp(PROPOSITIONS.evidence + String.raw`|\d\s?(?:%|per ?cent|percent)|\b(?:rises?|falls?|drops?|grows?|slows?|doubles?|nears|tops|assess\w*|review\w*)\b`, 'i'), 2],
  ['diplomatic development', new RegExp(PROPOSITIONS.diplomacy + String.raw`|\b(?:condemns?|rejects?|reacts?|sanctions?|suspends?|wins?|awarded)\b`, 'i'), 2], ['scientific or technical advance', new RegExp(PROPOSITIONS.science + String.raw`|\b(?:detect(?:s|ed)?|sequenc\w+|commission(?:s|ed)?|induct(?:s|ed)?|world.s first)\b`, 'i'), 2],
  ['analysis of a problem or remedy', new RegExp(PROPOSITIONS.prescriptive, 'i'), 1.5],
  ['forecast or outlook', /\b(?:forecasts?|forecasted|predict(?:s|ed|ions?)?|projected|expected to|likely to|set to|to (?:continue|intensify|peak|form|strengthen|weaken|arrive|withdraw)|may (?:bring|encounter|trigger|hit|form|affect|see)|intensif\w+|onset|withdrawal)\b/i, 1.5],
  ['reported action', /\b(?:releas(?:es|ed)|rose|risen|ends?|ended|blasts? off|lifts? off|summon(?:s|ed)?|plans? to|planned|set to|aims? to|takes? (?:a )?step|takes? up|unlocks?|halts?|maintains|regains|hits|dips?|backs|discussing|gets?|to get|completes?|achieves?|becomes?|enters?|begins?|starts?|opens?)\b/i, 1.5],
]
const EXPLAINS = new RegExp(String.raw`^\s*(?:explained|decoded)\b|\|\s*explained\s*$|[:,]\s*(?:why|how|what)\b|^\s*(?:why|how|what)\b|` + String.raw`\b(?:what (?:is|are|does|do|it means|this means|we know|to know)|explained|explainer|expert explains|key takeaways|in graphics|knowledge nugget|upsc key)\b`, 'i')
const sourceOf = new Map(NEWS_SOURCES.map(s => [s.id, s]))

/** Institutions whose decisions apply to the whole country, and bodies whose findings are cited worldwide. */
const NATIONAL = new RegExp(String.raw`\b(?:Centre|Union (?:government|Cabinet|Minister|Budget|Health|Home|Finance)|Cabinet (?:approves|clears|nod)|Parliament(?:ary)?|Lok Sabha|Rajya Sabha|Supreme Court|SC|RBI|SEBI|GST Council|NITI Aayog|ISRO|DRDO|Navy|IAF|Army|Armed Forces|ICMR|NGT|CAG|ECI?|Election Commission|Finance (?:Ministry|Commission)|Govt|Government of India|MEA|MHA|PMO|Registrar General|Railways|Indian Railways|NHAI|TRAI|IMD|NPCI|NPPA|CEA|DPIIT|Coal Ministry|\w+ Ministry|Ministry of \w+|India(?:’s|'s)?|Indian|national|nationwide|pan-India|all States)\b`)
const GLOBAL_BODY = new RegExp(String.raw`\b(?:UN|UNSC|UNGA|UNCTAD|UNESCO|UNICEF|UNEP|UNDP|WHO|IMF|World Bank|WTO|IPCC|WMO|IEA|FAO|IFAD|ILO|IUCN|ICC|ICJ|IAEA|FATF|OPEC\+?|BRICS|G20|G7|ASEAN|EU|NATO|SCO|Quad|OECD|ADB|Nobel|COP ?\d{2}|U\.N\.|W\.T\.O\.)\b`)
/** The institution and its act, adjacent in the headline: the decision itself rather than talk about it. */
const DECISION = /\b(?:RBI|SEBI|Centre|Govt|Government|Cabinet|SC|Supreme Court|GST Council|Parliament|Lok Sabha|Rajya Sabha|NGT|ISRO|DRDO|Navy|IAF|Army|India|TRAI|IRDAI|NITI Aayog|ECI?|CAG)\s+(?:to\s+)?(?:raises?|cuts?|hikes?|caps?|orders?|approves?|clears?|notif(?:y|ies)|bans?|withdraws?|launch(?:es)?|proposes?|imposes?|amends?|allows?|permits?|recommends?|unveils?|finali[sz]es?|extends?|mandates?|scraps?|signs?|joins?|issues?|directs?|eases?|tightens?|cancels?|rules|strikes down|upholds?|allots?|commissions?|inducts?|test.fires?|tests|passes|ratifies|implements?|releases?|sets up|constitutes|revises?)\b/
const INDICATOR = /\b(?:GDP|GVA|PMI|IIP|CPI|WPI|GST (?:revenue|collections?)|forex reserves|inflation|fiscal deficit|current account deficit|trade deficit|unemployment rate|industrial production|core sector|monsoon|rain(?:fall)? deficit|exports|imports|FDI|repo rate|CRR)\b/i
const INDIA = new RegExp(String.raw`\b(?:India(?:n|ns|’s|'s)?|Bharat|New Delhi|Centre|Modi|Jaishankar|Sitharaman|rupee|MEA|RBI|ISRO|IAF|Air Chief|Army Chief|Navy Chief|Indo-\w+)\b|₹`)

const STATES = String.raw`Andhra(?: Pradesh)?|A\.P\.|Arunachal(?: Pradesh)?|Assam|Bihar|Chhattisgarh|Goa|Gujarat|Haryana|Himachal(?: Pradesh)?|Jharkhand|Karnataka|Keralam?|Madhya Pradesh|M\.P\.|MP|Maharashtra|Manipur|Meghalaya|Mizoram|Nagaland|Odisha|Orissa|Punjab|Rajasthan|Sikkim|Tamil Nadu|T\.N\.|TN|Telangana|Tripura|Uttarakhand|West Bengal|Bengal|J&K|Jammu(?: and Kashmir)?|Puducherry|Delhi|Mumbai|Kolkata|Chennai|Bengaluru|Hyderabad|Ahmedabad|Pune|Jaipur|Patna|Bhopal|Guwahati|Srinagar|Kochi|Kozhikode|Mysuru|Noida|Gurugram|Lucknow|Chandigarh|Thiruvananthapuram|Visakhapatnam|Nagpur|Indore|Mangaluru|Madurai|Coimbatore`
/** A State's own institutions acting on its own business. Uttar Pradesh is kept for UPPCS. */
const STATE_ACTOR = new RegExp(String.raw`\b(?:${STATES}|State|state)(?:’s|'s)? (?:govt\.?|government|Cabinet|Assembly|police|Police|HC|High Court|CM|Chief Minister|Minister|minister|Bar Council|Information Commission|FDA|officials?)\b|\b(?:CM|Chief Minister|HC|High Court|Collectors?|DGP|MLAs?|Corporation|Commissioner|district|Dy CM|deputy CM|Lokayukta)\b|\b(?:${STATES}) (?:orders|launches|draws|tops|to make|advises|deploys|reshuffle|loses)\b|\b(?:Fadnavis|Stalin|Vijayan|Naidu|Revanth|Siddaramaiah|Mamata|Nitish|Yogi|Kejriwal|Lalduhoma|Satheesan|Mann|Sarma|Shinde|Dhami|Majhi|Soren|Sukhu|Saini)\b`)
const STATE_NAME = new RegExp(String.raw`\b(?:${STATES})\b`)
const POLITICS = new RegExp(String.raw`\b(?:BJP|Congress|AAP|TMC|DMK|AIADMK|TVK|BRS|CPI(?:\(M\))?|SP|BSP|RJD|JD\(U\)|NDA|INDIA bloc|Opposition|Oppn|CJP|Cockroach|AISA|SFI|party|parties|Rahul(?: Gandhi)?|Priyanka|Kharge|Chirag Paswan|Owaisi|Thackeray|Akhilesh|Mayawati)\b|\b(?:protests?|protesters?|stir|agitation|march|rally|bandh|hartal|sit.in|dharna|shutdown of|detained|detention of|slogans?|by.?polls?|by.?elections?|election results?|polls? results?|unopposed|wins? (?:seat|both|in)|sweeps?|trounces?|alleges?|slams?|hits? (?:back|out)|targets|takes? a dig|resign\w*|ouster|row|jibe|salvo|potshots?|vote chori|war of words|memorandum|menu)\b`, 'i')
/** Case-level litigation: a party's step in a dispute, not a ruling others must follow. */
const LITIGATION = new RegExp(String.raw`\b(?:pleas?|petitions?|FIRs?|probe|bail|acquit\w*|junks?|recus\w+|contempt notices?|court summons|chargesheet|custody|remand|defamation|moves (?:court|HC|SC|Supreme Court|High Court|apex court)|challenged (?:in|before)|seeks? (?:reply|replies|response|probe|report)|raps|pulls up|hostile|alimony|divorce|inquest|case against|booked|raids?|searches|arrests?|arrested|nabs|busts|seizes)\b`, 'i')
const STATEMENT = new RegExp(String.raw`[:,]\s*(?:says\s+)?[A-Z][\w.’'-]+(?:\s+[A-Z(][\w.’'()-]+){0,4}\.?\s*$|\b(?:says|said|asks|urges|tells|told|warns|hails|calls for|calls on|vows|pitches|backs|questions|slams|reacts|responds|replies|clarifies|welcomes|pushes back|writes to|message to)\b|^\s*[‘'"“]`)
const INSTITUTION_VOICE = new RegExp(String.raw`[:,]\s*(?:(?:says|clarifies|rules|warns|finds)\s+)?(?:(?:S\.? )?Jaishankar|Sitharaman|PM Modi|CJI|Air Chief|Army Chief|Navy Chief|CDS|FM|EAM|RBI Governor|Foreign Secretary|RBI|SEBI|Centre|Govt|Government|Supreme Court|SC|MEA|WMO|IMF|World Bank|WTO|UN[A-Z]*|WHO|IEA|IMD|ISRO|NITI Aayog|CAG|Report|Study|Survey|UN trade body|House panel|Parliamentary panel)\b[^,:]*$|\b(?:RBI|SEBI|Centre|Supreme Court|SC|MEA|WMO|IMF|World Bank|WTO|WHO|ISRO|UN) (?:says|warns|tells|asks|clarifies)\b`)
const CONSUMER = new RegExp(String.raw`^\s*Top \d+\b|\b(?:you|your|yours)\b|\bshould (?:you|investors)\b|\b(?:guide to|full list|check (?:list|details|here)|what.s open|here.s (?:how|what|why)|know why|tips|dos and don.ts|how to (?:spot|buy|save|check|apply|shield|claim)|when and where|all you need to know|step.by.step|portfolios?|net worth|salary|mansion|estate for)\b`, 'i')
const CORPORATE = new RegExp(String.raw`\b(?:TCS|Infosys|Infy|Wipro|HCL|Cognizant|Capgemini|Microsoft|Tesla|Starbucks|Chipotle|Nvidia|OpenAI|Anthropic|Claude|ChatGPT|Meta|Amazon|Apple|Google|DeepMind|TikTok|Adani|Reliance|Ambani|Tata|Airtel|Jio|HDFC|ICICI|IndiGo|Air India|Akasa|Essar|TSMC|Adidas|Delta|Verizon|AT&T|Zuckerberg|Musk|Nadella|Bezos|Altman)\b|\b(?:stocks?|investors?|IPO|listing|valuations?|earnings|net profit|takeover|recalls?|recalled|borrowing spree|bull market|startup founders?|experience cent(?:re|er)|showroom|CEO|market value|supervisory board|independent director|brand|bets big|secures?|bags|contracts?|order book)\b`)
const ROUTINE = new RegExp(String.raw`\b(?:to (?:discuss|meet|hold|celebrate|chair)|special (?:Cabinet )?meet|awareness|celebrated|tribute|honou?rs?|felicitat\w+|inaugurat\w+|flags? off|workshop|conference|seminar|pays? homage|greets|condoles?|braces for|on standby|gets new|office bearers|timings|cancelled|rescheduled|diverted|closed|shut|full list|LIVE|Highlights|wrap|brief)\b`)
const PERSON = new RegExp(String.raw`\b(?:who is|who was|5 (?:facts|things)|timeline|life dedicated|bus driver.s daughter|obituary|dies|died|dead|death of|passes away|found dead|birthday|biography|interview|writes:|writes \|)\b`, 'i')
/** Places and marks of another country's own affairs. */
const FOREIGN = new RegExp(String.raw`\b(?:US|U\.S\.|UK|U\.K\.|America(?:n|ns)?|Britain|British|England|Scotland|Wales|London|Europe(?:an)?|France|French|German(?:y)?|Ital(?:y|ian)|Spain|Spanish|Russia(?:n)?|Ukrain(?:e|ian)|Chin(?:a|ese)|Hong Kong|Hongkongers|Japan(?:ese)?|Korea(?:n)?|Australia(?:n)?|Sydney|Canad(?:a|ian)|Brazil(?:ian)?|Mexic(?:o|an)|Israel(?:i)?|Iran(?:ian)?|Iraq|Syria|Turk(?:ey|ish)|Egypt(?:ian)?|Saudi|UAE|Qatar|Nigeria|Kenya|Sudan|South Africa(?:n)?|Ethiopia|Eritrea|Indonesia(?:n)?|Vietnam|Philippines|Singapore|Thailand|Malaysia(?:n)?|Venezuela|Argentina|Poland|Hungary|Estonia|Netherlands|Dutch|Trump|Biden|Vance|White House|Pentagon|California|Texas|Florida|New York|NYC|Kyiv|Moscow|Beijing|Tokyo|Paris|Berlin|Brussels|Labour|Tory|Tories|Starmer|Burnham|Macron|Putin|Xi|Pakistan(?:i)?|Nepal(?:i)?|Bangladesh(?:i)?|Sri Lanka(?:n)?|Myanmar|N\.I\.H|Fed|Federal Reserve|Wall Street|Gulf coast|Atlantic)\b`)
const NEIGHBOUR = /\b(?:Nepal|Bhutan|Bangladesh|Sri Lanka|Maldives|Myanmar|Pakistan|Afghanistan|Tibet|Himalayas?|Himalayan|Indian Ocean|South Asia)\b/
const FOREIGN_DOMESTIC = new RegExp(String.raw`\b(?:households?|residents|neighbours|utility companies|council|county|mayor|governor|midterms?|by.?election|local election|senate|senators?|congress(?:ional)?|lawmakers|republicans?|democrats?|parliament|ministers|students|schools?|universit(?:y|ies)|police|court|judge|lawsuit|mortgage|housing|rent|pension|taxpayers|public purse|public square|festival|museum|winery|£|\$\d|US\$|€)\b|[£€]`, 'i')
const titleCase = (title: string) => { const words = title.split(/\s+/).filter(w => /^\p{L}{3,}/u.test(w) && !/^(?:the|and|for|with|from|into|its|over)$/.test(w)); return words.length >= 5 && words.filter(w => /^\p{Lu}/u.test(w)).length / words.length > 0.8 }
/** Content written to fill a feed rather than report: dated trivia, and bylined comment from abroad. */
const TRIVIA = /^\s*In \d{4},\s/, FOREIGN_COMMENT = /\|\s*[A-Z][\p{L}.'’-]+(?:\s+[A-Z][\p{L}.'’-]+){1,2}\s*$/u
const noiseTerms = (() => { const m = new PhraseMatcher<NoiseCategory>(); NOISE.forEach((n, i) => n.terms.forEach(term => m.add(term, n, String(i)))); return m })()
/** v2 noise categories this policy states in its own terms; the rest keep their points. */
const RESTATED = new Set(['politics', 'corporate', 'routine', 'court-routine'])
const compiled = TOPICS.map(topic => ({ topic, loose: topic.terms ? new RegExp(String.raw`(?<![\p{L}\p{N}])(?:${topic.terms})(?![\p{L}\p{N}])`, 'iu') : null, cased: topic.cased ? new RegExp(String.raw`(?<![\p{L}\p{N}])(?:${topic.cased})(?![\p{L}\p{N}])`, 'u') : null }))
const first = (text: string, ...patterns: (RegExp | null)[]) => { for (const p of patterns) { const m = p?.exec(text); if (m) return m[0] } return null }
const round = (n: number) => Math.round(n * 10) / 10
/** Where an article with no topic of its own is shelved: the feed it arrived in. */
export function sectionSubject(item: Pick<NewsItem, 'section' | 'sourceId'>): Subject {
  const s = `${item.section} ${sourceOf.get(item.sourceId)?.subjectHints.join(' ') ?? ''}`
  return /environment|climate|wildlife/i.test(s) ? 'Environment' : /science|technolog|intelligence/i.test(s) ? 'Sci-Tech' : /world|international|asia|europe|middle east|global/i.test(s) ? 'International relations' : /econom|business|market|finance|agricultur/i.test(s) ? 'Economy' : 'Governance'
}
/** Every article is shelved under a syllabus subject: its own topic, else its dominant frame, else its feed. */
export function readingSubject(item: NewsItem, editorial: Pick<Editorial, 'subject'> = assess(item)): Subject {
  if (editorial.subject) return editorial.subject
  const framed = classifySubject(item).primary
  return framed === 'Unresolved' ? sectionSubject(item) : framed
}

/** `stageC` supplies the earlier stage's exclusions (price lists, live blogs, promotions); its admissions are not used. */
export function assess(item: NewsItem, stageC?: Pick<StageCDecision, 'eligibility'>): Editorial {
  const title = item.title, summary = item.description, text = `${title} ${summary}`, reasons: EditorialReason[] = []
  const add = (label: string, points: number, found?: string | null) => { if (points) reasons.push({ label, points: round(points), ...(found ? { text: found } : {}) }) }
  const source = sourceOf.get(item.sourceId), section = `${item.section} ${(item.memberships ?? []).map(m => m.section).join(' ')}`
  const finish = (subject: Subject | null, excluded?: string): Editorial => {
    const score = excluded ? 0 : round(reasons.reduce((n, r) => n + r.points, 0)), floor = subject ? EDITORIAL_POLICY.subjectFloor[subject] ?? EDITORIAL_POLICY.floor : EDITORIAL_POLICY.floor
    return { policy: EDITORIAL_POLICY.id, score, floor, accepted: !excluded && !!subject && score >= floor, subject, reasons, ...(excluded ? { excluded } : {}) }
  }
  // Formats that are never a reading: decided on the headline alone.
  const noise = new Map<NoiseCategory, string>(), words = tokenize(title)
  for (const hit of noiseTerms.scan(words)) if (!noise.has(hit.value)) noise.set(hit.value, words.slice(hit.start, hit.start + hit.length).map(x => x.raw).join(' '))
  const never = [...noise].find(([category]) => category.hard || category.id === 'digest')
  if (never) return finish(null, `${never[0].label} (“${never[1]}”)`)
  const gate = stageC?.eligibility.status === 'reject' ? stageC.eligibility.reasonCodes.find(code => /^C1\.(?!party_primary|foreign_domestic)/.test(code)) : undefined
  if (gate) return finish(null, gate)
  if (TRIVIA.test(title)) return finish(null, 'Dated trivia')

  // Topics: the strongest in the headline carries the article; a summary-only topic counts for half.
  const bySubject = new Map<Subject, number>(), hits: { topic: Topic; inTitle: boolean; found: string }[] = []
  for (const { topic, loose, cased } of compiled) {
    const inTitle = first(title, loose, cased), found = inTitle ?? first(summary, loose, cased)
    if (found) hits.push({ topic, inTitle: !!inTitle, found })
  }
  if (!hits.length) return finish(null, 'No syllabus topic in headline or summary')
  const points = (h: typeof hits[number]) => h.topic.weight * (h.inTitle ? 1 : 0.5)
  hits.sort((a, b) => points(b) - points(a) || EDITORIAL_POLICY.subjectPriority[b.topic.subject] - EDITORIAL_POLICY.subjectPriority[a.topic.subject])
  for (const h of hits) bySubject.set(h.topic.subject, (bySubject.get(h.topic.subject) ?? 0) + points(h))
  const subject = [...bySubject].sort((a, b) => b[1] - a[1] || EDITORIAL_POLICY.subjectPriority[b[0]] - EDITORIAL_POLICY.subjectPriority[a[0]])[0][0]
  const lead = hits.find(h => h.topic.subject === subject)!, support = hits.find(h => h !== lead && h.topic.id !== lead.topic.id)
  add(`${subject}: ${lead.topic.id}${lead.inTitle ? '' : ' (summary only)'}`, points(lead), lead.found)
  if (support) add(`Second topic: ${support.topic.id}`, Math.min(1, 0.4 * points(support)), support.found)

  // Development: what happened. An explainer or editorial is a development of its own kind.
  let developed = 0
  // "Raises concerns" raises nothing.
  const reported = title.replace(/\b(?:raises?|raising|raised)\s+(?:concerns?|fears?|questions?|alarm|doubts?|eyebrows|hopes?)\b/gi, 'worries')
  for (const [label, pattern, worth] of DEVELOPMENTS) {
    // A word inside the topic's own name ("Jal Jeevan Mission") is not something that happened.
    const named = first(reported, pattern), inTitle = named && hits.some(h => h.inTitle && h.found.toLowerCase().includes(named.toLowerCase())) ? null : named, found = inTitle ?? first(summary, pattern)
    if (!found) continue
    const value = Math.min(inTitle ? developed ? 0.5 : worth : developed ? 0 : 1, 3 - developed)
    developed += value; add(`${label}${inTitle ? '' : ' (summary only)'}`, value, found)
  }
  // A headline that asks and answers is an explainer wherever it runs; an Explained section alone is weaker evidence.
  const comment = source?.kind === 'international' && FOREIGN_COMMENT.test(title)
  const finding = /\b(?:study|studies|scientists?|researchers?|research|discover\w*|finds?|found|sequenc\w+|detect\w*|fossils?)\b/i.test(title)
  const explained = EXPLAINS.test(title) || item.sourceId === 'dte-news' || source?.kind === 'newsletter'
  const opinion = !comment && /editorial|opinion|columns?|op-ed|lead/i.test(section), desk = /explained|explainer|upsc/i.test(section)
  if (explained) add('Explainer', 2.5); else if (/editorial|lead/i.test(section)) add('Editorial', 2); else if (opinion || desk) add('Opinion, analysis or explainer section', 1)
  if (/^(?:ie-explained|ht-explained)/.test(item.sourceId) && explained) add('Explainer desk', 1)
  if (item.sourceId.startsWith('ie-upsc')) add('Publisher-curated UPSC section', 1)
  if (!developed && !explained && !opinion) add('No development reported', -2)

  // A State's Cabinet, government or minister is not the Union's.
  const stateActor = item.sourceId === 'et-uttarpradesh' ? null : first(title, STATE_ACTOR), own = (found: string | null) => found && stateActor && /^(?:Cabinet|Govt|Government)/.test(found) ? null : found
  const national = own(first(title, NATIONAL)), body = first(title, GLOBAL_BODY)
  if (body) add('International body or award', 1.5, body); else if (national) add('National institution or scope', 1.5, national)
  else if (first(summary, GLOBAL_BODY, NATIONAL)) add('National or international scope (summary only)', 0.5)
  add(`${subject} priority`, EDITORIAL_POLICY.subjectPriority[subject])
  add('Feed prior', EDITORIAL_POLICY.sourcePrior[item.sourceId] ?? 0)
  const indicator = first(title, INDICATOR)
  if (indicator && /\d/.test(title)) add('Headline indicator with its figure', 1, indicator)

  const decision = own(first(title, DECISION))
  if (decision) add('Decision by a national institution', 1.5, decision)
  // What lowers the value of a syllabus topic.
  const indian = INDIA.test(text) || !!national
  // An explainer's occasion (a protest, a State, a company) is not its subject.
  const soften = explained ? 0.5 : 1
  const politics = first(title, POLITICS)
  if (politics) add('Party politics, protest or election contest', explained ? -0.5 : -4, politics)
  const litigation = first(title, LITIGATION)
  if (litigation) add('Case-level litigation or police action', -3 * soften, litigation)
  const stateName = first(title, STATE_NAME)
  const placeBound = subject === 'Environment' || subject === 'Geography' || subject === 'History & Culture'
  if (stateActor) add('State or local administration', (national || body ? -1.5 : -3) * soften, stateActor)
  else if (stateName && !national && !body && !explained) add('Single State or city', placeBound ? -0.5 : -1.5, stateName)
  const voiced = first(title, STATEMENT)
  if (voiced && !INSTITUTION_VOICE.test(title) && !explained) add('Report of a remark', -2.5, voiced.trim())
  const consumer = first(title, CONSUMER)
  if (consumer) add('Consumer or personal-finance advice', -4, consumer)
  const corporate = first(title, CORPORATE)
  if (corporate) add('Company or market story', explained && indian ? -1.5 : -3, corporate)
  const routine = first(title, ROUTINE)
  if (routine) add('Routine or ceremonial', -2, routine)
  const person = first(title, PERSON)
  if (person && !opinion) add('Profile or obituary', -2, person)
  // A national institution acting on crashes or crime is policy, not a casualty report.
  for (const [category, phrase] of noise) if (!RESTATED.has(category.id) && !((category.id === 'accident' || category.id === 'crime') && national && developed >= 2)) add(`${category.label}`, Math.max(category.points, -4), phrase)
  // Another country's own affairs: kept only for science, a global body, the neighbourhood's bearing on India or a systemic conflict.
  const foreign = first(title, FOREIGN)
  if (foreign && !indian) {
    const domestic = first(title, FOREIGN_DOMESTIC), knowledge = subject === 'Sci-Tech' || subject === 'Environment' || subject === 'Geography'
    const systemic = !!body || hits.some(h => h.inTitle && (h.topic.id === 'conflict' || h.topic.id === 'groupings'))
    if (domestic) add('Another country’s domestic affairs', -4, `${foreign}; ${domestic}`)
    else if (!knowledge && !systemic) add('Set abroad with no India link or systemic effect', -2.5, foreign)
    else if (knowledge && !body && !NEIGHBOUR.test(title)) add('Set abroad', finding ? -1 : -2.5, foreign)
  } else if (!indian && source?.kind === 'international' && !body) add('International feed, no India link', subject === 'Polity' || subject === 'Governance' || subject === 'Economy' ? -3 : finding ? -1.5 : -2.5)
  if (comment) add('Bylined comment from abroad', -1.5)
  if (source?.kind === 'newspaper' && /business/i.test(item.section) && titleCase(title)) add('Promotional headline style', -5)
  if (stageC?.eligibility.status === 'reject') add('Party-led or foreign-domestic framing', -3, stageC.eligibility.reasonCodes.join(', '))
  return finish(subject)
}
