/** Shared syllabus vocabulary for Stage C routes and Stage D subject frames.
 * A domain names examinable objects (instruments, issues, phenomena), never bare
 * actors such as a court, a government, a party or a country. An object alone
 * never admits an article: Stage C also requires an independent substantive
 * proposition in the same field. Publishers, sections, authors, article
 * identities and PYQ frequency are absent. `terms` match case-insensitively;
 * `acronyms` match case-sensitively. */
export type LexiconSubject = 'Polity' | 'Governance' | 'Economy' | 'International relations' | 'Security' | 'Sci-Tech' | 'Environment' | 'Geography' | 'History & Culture'
export type Proposition = 'law' | 'court' | 'evidence' | 'diplomacy' | 'science' | 'prescriptive' | 'explain' | 'own'
export interface Domain {
  id: string; subject: LexiconSubject; scope: 'domestic' | 'knowledge' | 'systemic'
  terms: string; acronyms?: string
  /** Proposition classes that may support this domain; `own` is the domain's `support` pattern. */
  supports: readonly Proposition[]; support?: string; exceptional?: boolean
}
const join = (...parts: string[]) => parts.join('|')

/** Substantive propositions. `explain` is honoured in headlines only. */
export const PROPOSITIONS: Record<Exclude<Proposition, 'own'>, string> = {
  law: String.raw`\b(?:bills?|ordinance|amendments?|amends?|amended|notif(?:y|ies|ied|ication)|draft (?:rules|policy|bill|guidelines|norms)|guidelines|polic(?:y|ies)|schemes?|regulations?|norms|reforms?|reformed|overhauls?|approv(?:es|ed|al)|clears|cleared|rolls? out|rollout|implement\w*|mandat(?:es|ed|ory)|bans?|banned|curbs?|scraps?|scrapped|repeals?|repealed|extends?|extended|hikes?|hiked|raises?|raised|cuts?|slash(?:es|ed)|revis(?:es|ed|ion)|rationali[sz]ation|simplification|allots?|allott?ed|allocat(?:es|ed|ion)|proposes?|proposed|defines?|introduc(?:es|ed)|tabled|passes|passed|enacts?|enacted|withdraws?|withdrawn|sets? up|constitutes|task force|programmes?|initiatives?)\b`,
  court: String.raw`\b(?:verdicts?|judge?ments?|ruling|ruled|strikes? down|struck down|upholds?|upheld|quash(?:es|ed)|sets? aside|stays?|stayed|refus(?:es|ed|al)|declin(?:es|ed)|dismiss(?:es|ed)|directs?|directed|directive|orders?|ordered|examine|hears?|hearing|pleas?|petitions?|refer(?:s|red)|larger bench|validity|recall|suo motu|invalid|precedent|liabilit(?:y|ies))\b`,
  evidence: String.raw`\b(?:reports?|study|studies|survey|data|index|estimates?|findings?|finds?|found|shows?|reveals?|assessment|audit|outlook|projections?|record(?:.breaking)?|ranking|surges?|declin(?:e|es|ed|ing))\b`,
  diplomacy: String.raw`\b(?:summits?|talks|agreements?|pacts?|treat(?:y|ies)|deal|joint statement|dialogue|sanctions|negotiat\w+|bilateral|trilateral|multilateral|partnership|cooperation|alliance|resolution|veto|ceasefire|truce|blockade|membership|presidenc(?:y|ies)|hosts?|mediat\w+|framework|declaration|agenda|expansion)\b`,
  science: String.raw`\b(?:launch(?:es|ed)?|missions?|discover\w*|breakthroughs?|develops?|developed|indigenous|first.ever|unveil(?:s|ed)|tests?|tested|test.fired|trials?|experiments?|mechanism|detectors?|solv(?:es|ed|ing)|uncover(?:s|ed)?|simulat\w+)\b`,
  prescriptive: String.raw`\b(?:must|should|needs? to|need for|lessons?|way forward|rethink\w*|implications?|dilemma|opportunity to|the case (?:for|against)|challenges?|cannot|concerns?|threat(?:s|en|ens|ening)?|risks?|crisis|impacts?)\b`,
  explain: String.raw`\b(?:why|how|what (?:is|are|does|do|it means|happens|went wrong|we know)|explained|explains?|explainer|decoded|takeaways?|matters)\b`,
}

export const DOMAINS: readonly Domain[] = [
  { id: 'constitutional-offices', subject: 'Polity', scope: 'domestic', exceptional: true, supports: ['court', 'law', 'prescriptive', 'explain'],
    terms: String.raw`appointment of (?:the )?(?:chief election commissioner|election commissioners?|judges|governors?|cec)|(?:cec|ecs?|election commissioners?|judges?|governors?)\b.{0,25}\bappointments?|appointment law|collegium|impeachment motion|president.s rule|governor.s (?:assent|powers?|role|discretion)|speaker.s (?:powers?|decision|ruling)|judicial (?:review|appointments?|overreach|accountability|reforms?|pendency)|contempt of court|tribunal reforms?` },
  { id: 'constitutional-law', subject: 'Polity', scope: 'domestic', exceptional: true, supports: ['court', 'law', 'prescriptive', 'explain', 'evidence'], acronyms: 'UCC|CAA|NRC|UAPA|PMLA|PIL',
    terms: String.raw`constitutional (?:amendment|validity|bench|morality|challenge)|constitution bench|basic structure|fundamental rights?|right to (?:privacy|life|equality|education|information|protest|vote|dissent)|article \d{1,3}[a-z]?\b|preventive detention|sedition|freedom of (?:speech|expression|religion|the press)|uniform civil code|reservation (?:policy|cap|quota|in promotions?)|(?:obc|ews|women.s) (?:quota|reservation)|creamy layer|sub.classification|places of worship act|citizenship (?:amendment )?act|anti.conversion law|waqf (?:act|law|amendment)|three.language (?:policy|formula)|official language|delimitation|anti.defection|tenth schedule|money bill|centre.state (?:relations|dispute)|inter.state (?:water|river|border) dispute|sixth schedule|fifth schedule|article 370|statehood|one nation,? one election|simultaneous elections` },
  { id: 'elections', subject: 'Polity', scope: 'domestic', supports: ['court', 'law', 'evidence', 'prescriptive', 'explain'], acronyms: 'SIR|EVMs?|VVPAT|NOTA',
    terms: String.raw`electoral rolls?|voter (?:lists?|rolls?|deletions?|registration|turnout)|special intensive revision|model code of conduct|electoral bonds?|election funding|political funding|campaign finance|postal ballots?|remote voting|representation of the people act|voting rights?|disenfranchis\w+` },
  { id: 'criminal-justice', subject: 'Polity', scope: 'domestic', supports: ['court', 'law', 'evidence', 'prescriptive', 'explain'], acronyms: 'BNS|BNSS|CrPC|NDPS|POCSO',
    terms: String.raw`body(?:.worn)? cameras?|custodial (?:deaths?|violence|torture)|police (?:reforms?|accountability|brutality)|encounter killings?|undertrials?|prison (?:reforms?|overcrowding)|bail (?:reforms?|jurisprudence|law)|death penalty|capital punishment|criminal (?:laws?|justice)|bharatiya nyaya sanhita|forensics?|victim identification|fast.track courts?|legal aid|pendency of cases|bulldozer (?:action|justice|demolitions?)|hate speech|mob lynching|data protection|right to be forgotten|surveillance|phone tapping|internet shutdowns?|affidavits?` },
  { id: 'welfare-delivery', subject: 'Governance', scope: 'domestic', supports: ['law', 'evidence', 'prescriptive', 'explain', 'court', 'own'], acronyms: 'PDS|MGNREGA|MGNREGS|NREGA|MSP|DBT|RTI|NFSA|EPFO|ESIC|CAG|PM-KISAN|SHGs?|NDMA|CAPFs?',
    support: String.raw`\b(?:pilferage|leakages?|savings|coverage|beneficiaries|delivery|digiti[sz]\w+|exclusions?|weed out|backlog|shortfall|tussle)\b`,
    terms: String.raw`public distribution system|ration (?:cards?|shops?)|food security act|mid.day meals?|pm poshan|anganwadis?|ayushman bharat|jan aushadhi|jal jeevan|swachh bharat|pm awas|ujjwala|direct benefit transfers?|welfare schemes?|social security (?:code|scheme|net)|pension scheme|unified pension|minimum support prices?|crop insurance|fasal bima|self.help groups?|rural employment|employment guarantee|skill development|internship scheme|gig workers?|platform workers?|labou?r codes?|minimum wages?|migrant workers?|manual scavenging|social audit|caste (?:census|certificates?)|national population register|aadhaar|digital public infrastructure|e.governance|public service delivery|service delivery|right to information|civil services? reforms?|lateral entry|administrative reforms?|panchayats?|panchayati raj|gram sabhas?|urban local bod(?:y|ies)|municipal (?:finances?|bonds?|governance)|smart cit(?:y|ies)|disaster management|road safety|traffic fatalities|public transport|urban flooding|affordable housing|slum (?:rehabilitation|redevelopment)|land (?:records|acquisition|reforms?)|encroachment of (?:public )?land` },
  { id: 'education-health', subject: 'Governance', scope: 'domestic', supports: ['law', 'court', 'evidence', 'prescriptive', 'explain', 'own'], acronyms: 'NEP|UGC|NEET|ASER|NFHS|AMR|ICMR|CDSCO',
    support: String.raw`\b(?:accountability|outcomes?|disclos\w+|shortages?)\b`,
    terms: String.raw`national education policy|higher education|(?:private|pvt|public|central|state) universit(?:y|ies)|school education|education system|learning outcomes?|foundational literacy|dropout rates?|teacher (?:shortage|vacancies|training)|medical education|coaching (?:centres?|industry)|entrance exams?|paper leaks?|public health|health (?:insurance|coverage|expenditure|model|system|infrastructure)|primary health\w*|universal health|malnutrition|stunting|anaemia|maternal mortality|infant mortality|fertility rate|life expectancy|tuberculosis|non.communicable diseases?|antimicrobial resistance|mental health (?:policy|care|crisis)|drug (?:pricing|regulation|regulator)|generic (?:drugs|medicines)|vaccination (?:drive|coverage|programme)|immuni[sz]ation|tobacco control|sanitation` },
  { id: 'macro-finance', subject: 'Economy', scope: 'domestic', supports: ['law', 'evidence', 'prescriptive', 'explain'], acronyms: 'GDP|GVA|CAD|GST|FDI|FPI|NPAs?|NBFCs?|IBC|UPI|CBDC|FCNR(?:\\(B\\))?|MPC|SEBI|IIP|PLFS|FDs',
    terms: String.raw`gross domestic product|economic growth|growth (?:forecast|outlook|estimate|rate|sacrifice)|inflation|consumer price|wholesale price|fiscal deficit|revenue deficit|current account deficit|trade deficit|balance of payments|forex reserves?|foreign exchange reserves?|rupee (?:depreciation|falls?|slides?|weakens|value|internationali[sz]ation)|exchange rate|repo rate|interest rates?|deposit rates?|lending rates?|monetary policy|bond yields?|government (?:bonds?|securities|borrowing)|public debt|sovereign rating|credit rating|capital expenditure|capex|union budget|budget (?:estimates?|allocation)|tax (?:revenue|collections?|devolution|reforms?|buoyancy)|direct tax(?:es)?|income.tax (?:bill|act|slabs?|law)|i.t bill|gst (?:rates?|council|collections?|rationali[sz]ation|compensation|slabs?)|goods and services tax|customs dut(?:y|ies)|subsid(?:y|ies)|disinvestment|privati[sz]ation|public sector (?:banks?|undertakings?|enterprises?)|bank (?:credit|deposits?|mergers?|recapitali[sz]ation)|non.performing assets?|bad loans?|insolvency|financial inclusion|digital payments?|central bank digital currency|cryptocurrenc(?:y|ies)|household savings|savings (?:rate|accounts?)|unemployment|labou?r force|job creation|employment data|wage growth|per capita income|poverty (?:line|rate|estimates?)|billionaire wealth|remittances|foreign direct investment|capital flows?|external commercial borrowings?` },
  { id: 'sectors-trade', subject: 'Economy', scope: 'domestic', supports: ['law', 'evidence', 'prescriptive', 'explain', 'diplomacy', 'court'], acronyms: 'FTA|CEPA|PLI|GCCs?|MSMEs?|SMEs?|EVs?|PNGRB|TRAI|IRDAI|NHAI|OPEC\\+?',
    terms: String.raw`free trade agreements?|trade (?:deal|pact|talks|policy|war|barriers?|surplus|ties)|tariffs?|export (?:curbs?|ban|duty|controls?|incentives?)|import (?:curbs?|ban|duty|dependence|substitution)|supply chains?|critical minerals?|rare earths?|semiconductors?|chip (?:manufacturing|fabs?|war)|manufacturing (?:scheme|sector|hub|push)|production.linked incentives?|make in india|electronics manufacturing|start.?ups?|deep.tech|it (?:sector|services)|indian tech|global capability cent(?:re|er)s?|gig economy|e.commerce (?:policy|rules)|agricultur\w+ (?:reforms?|exports?|credit|marketing|subsid\w+|income|sector)|farm (?:laws?|income|loan waiver|sector|exports?)|farmers?|food (?:prices|spending|processing|grain stocks?)|fertili[sz]er subsid\w+|crop (?:yields?|diversification|prices)|horticulture|fisheries|dairy sector|infrastructure (?:pipeline|spending|investment)|national highways?|railways|freight corridors?|major ports|shipbuilding|aviation sector|airlines|telecom (?:sector|spectrum|tariffs?)|spectrum (?:auction|allocation|allotment)|satellite internet (?:spectrum)?|power sector|electricity (?:demand|tariffs?|reforms?)|discoms?|coal (?:production|imports?|sector)|oil imports?|crude (?:oil )?imports?|energy security|strategic petroleum reserves?|refiners|natural gas|ethanol blending|electric vehicles?|green hydrogen|solar (?:power|capacity|boom|manufacturing|energy)|renewable (?:energy|capacity)|nuclear (?:power|energy|liability|ambitions?)|uranium (?:deal|supply|imports?|reserves?)|copper prices?|gold (?:imports?|reserves?)|commodity prices|real estate (?:sector|regulation)|insurance (?:sector|reforms?)|corporate governance|competition (?:law|commission)|antitrust|listing (?:norms|rules)|upper layer` },
  { id: 'foreign-policy', subject: 'International relations', scope: 'domestic', supports: ['diplomacy', 'prescriptive', 'explain', 'law'], acronyms: 'BITs?|LAC|LoC|H-1B',
    terms: String.raw`bilateral investment treat(?:y|ies)|investment treat(?:y|ies)|extradition (?:treaty|request)|indus waters treaty|border (?:talks|dispute|agreement|pact)|line of actual control|strategic partnership|comprehensive (?:economic|strategic) partnership|defen[cs]e (?:pact|agreement|cooperation)|civil nuclear (?:deal|agreement|cooperation)|foreign policy|strategic autonomy|non.alignment|multi.alignment|neighbou?rhood (?:first|policy)|act east|global south|indo.pacific|diaspora|visa (?:regime|rules|curbs|policy)|deportations?|2\+2 dialogue|de.risk|decoupl\w+` },
  { id: 'multilateral-order', subject: 'International relations', scope: 'systemic', supports: ['diplomacy', 'explain', 'own'], acronyms: 'BRICS|G20|G7|SCO|Quad|QUAD|ASEAN|SAARC|BIMSTEC|UNSC|UNGA|UNHRC|WTO|IMF|NATO|IAEA|FATF|ICJ|UNCLOS|NPT|AUKUS',
    support: String.raw`\b(?:reforms?|dilemma|alternative|call on|fractious)\b`,
    terms: String.raw`united nations|security council|world bank|world trade organi[sz]ation|international monetary fund|international court of justice|international criminal court|shanghai cooperation|european union|african union|arctic (?:council|security)|global governance|international order|rules.based order|multilateralism|multipolar\w*|world order|global economic order` },
  { id: 'conflict-geopolitics', subject: 'International relations', scope: 'systemic', supports: ['diplomacy', 'explain', 'own'],
    support: String.raw`\b(?:security strateg(?:y|ies)|regional order|escalat\w+|worries for india|progress on talks|nuclear question)\b`,
    terms: String.raw`\b(?:us|u\.s\.|israel|iran|russia|ukraine|india|pakistan|china|taiwan|lebanon|denmark|trump|xi|eu)[-–](?:us|u\.s\.|israel|iran|russia|ukraine|india|pakistan|china|taiwan|lebanon|denmark|trump|xi|eu) (?:war|conflict|ceasefire|deal|talks|tensions|ties|relations|summit|pact|standoff|truce|framework)|west asia (?:war|conflict|crisis)|middle east (?:war|conflict|crisis)|gulf states|gulf (?:security|monarchies|cooperation council)|ukraine war|gaza (?:war|ceasefire|peace plan)|south china sea|korean peninsula|nuclear (?:talks|deal|programme|program)|arms race|great.power (?:rivalry|competition)|war crimes|peace (?:talks|plan|process)` },
  { id: 'sea-lanes', subject: 'Security', scope: 'systemic', exceptional: true, supports: ['own'],
    // A place name is not a development: only stated systemic trade or energy consequences qualify.
    support: String.raw`\b(?:shipping route|energy (?:exports?|trade|supplies|flows?)|oil (?:exports?|supply|flows?)|global (?:trade|commerce|supply)|trade through|restricted trade|supply chains?|freight (?:rates|costs)|world market|must end)\b`,
    terms: String.raw`bab el.mandeb|strait of hormuz|red sea|suez canal|strait of malacca|malacca strait|taiwan strait|commercial shipping|sea lanes?|maritime chokepoints?|freedom of navigation` },
  { id: 'defence-internal-security', subject: 'Security', scope: 'domestic', supports: ['law', 'evidence', 'prescriptive', 'explain', 'own'], acronyms: 'DRDO|HAL|CDS|BSF|CRPF|ITBP|NSG|AFSPA|LWE|ATGMs?|S-400|BrahMos|Rafale|Tejas',
    support: String.raw`\b(?:test.fired|inducts?|inducted|commission(?:s|ed)|procure\w*|indigenous|doctrine|capabilit(?:y|ies)|strategy)\b`,
    terms: String.raw`defen[cs]e (?:procurement|acquisition|exports?|budget|production|reforms?|indigeni[sz]ation|manufacturing)|theatre commands?|chief of defen[cs]e staff|agnipath|agniveers?|fighter jets?|aircraft carriers?|submarines?|missile (?:test|systems?|defen[cs]e)|ballistic missiles?|hypersonic|air defen[cs]e|anti.tank|drone warfare|border (?:infrastructure|security|fencing|management)|ceasefire violations?|cross.border terror\w*|counter.?terror\w*|terror (?:financing|funding)|left.wing extremism|maoists?|naxal\w*|insurgenc(?:y|ies)|internal security|coastal security|maritime security|cyber ?(?:security|attacks?|crime|fraud)|official secrets act|intelligence (?:reforms?|agencies)|nuclear (?:doctrine|triad|deterrence)|military (?:exercise|moderni[sz]ation|reforms?)` },
  { id: 'science-frontier', subject: 'Sci-Tech', scope: 'knowledge', supports: ['science', 'evidence', 'explain', 'prescriptive', 'law'], acronyms: 'NISAR|PSLV|GSLV|SSLV|EOS-\\d+|NavIC|AI|LIGO|ITER|LLMs?',
    terms: String.raw`nobel (?:prize )?(?:in |for )?(?:physics|chemistry|medicine|physiology)|(?:physics|chemistry|medicine) nobel|satellites?|launch vehicles?|space (?:station|mission|programme|program|policy|sector|debris|telescope)|lunar (?:mission|lander|polar)|moon mission|mars mission|astronauts?|human spaceflight|chandrayaan\S*|gaganyaan|black holes?|dark matter|dark energy|neutrinos?|gravitational waves|exoplanets?|asteroids?|quantum (?:computing|computers?|communication|technology|sensing|mission)|decoherence|nuclear fusion|fusion (?:reactor|energy)|small modular reactors?|thorium|fast breeder|particle (?:physics|accelerator|collider)|gene (?:editing|therapy)|crispr|genome (?:sequencing|project)|stem cells?|mrna|vaccines?|cancer (?:drug|therapy|vaccine)|biotechnolog\w+|gm crops?|genetically modified|synthetic biology|artificial intelligence|generative ai|large language models?|machine learning|supercomput\w+|semiconductor (?:mission|fab)|blockchain|deepfakes?|data cent(?:re|er)s?|offshore aquifers?|superconduct\w+|nanotechnolog\w+|solid.state batter(?:y|ies)|fossils?(?![ -]fuel)|dinosaurs?|pala?eontolog\w+|human evolution|indian science` },
  { id: 'conservation', subject: 'Environment', scope: 'domestic', supports: ['law', 'court', 'evidence', 'prescriptive', 'explain', 'own'], acronyms: 'IUCN|CITES|NTCA|CAMPA',
    support: String.raw`\b(?:efforts|breeding|habitats?|population|recovery|symbolism|translocat\w+|reintroduc\w+)\b`,
    terms: String.raw`\w+ conservation|conservation (?:efforts|plan|strategy|project|breeding|reserve|status)|wildlife (?:protection|trade|corridors?|sanctuar(?:y|ies)|board|act)|project (?:tiger|cheetah|elephant|dolphin|lion)|bustards?|tiger (?:reserves?|population|census|deaths?)|elephant corridors?|cheetah (?:reintroduction|project|deaths?)|vultures?|gharials?|snow leopards?|asiatic lions?|olive ridley|gangetic dolphins?|endangered species|invasive species|species (?:extinction|recovery|loss)|biodiversity|protected areas?|national parks?|biosphere reserves?|eco.sensitive zones?|wetlands?|ramsar|mangroves?|forest (?:cover|rights|fires?|clearance|diversion|survey)|deforestation|afforestation|western ghats|aravallis?|sundarbans?|man.animal conflict|human.wildlife conflict|sacred groves?|seed banks?|crop diversity` },
  { id: 'climate-environment', subject: 'Environment', scope: 'knowledge', supports: ['law', 'court', 'evidence', 'prescriptive', 'explain', 'diplomacy', 'own'], acronyms: 'COP\\d{2}|UNFCCC|IPCC|NGT|EIA|CPCB|AQI|GRAP|NDCs?|CBAM',
    support: String.raw`\b(?:food security|collaps(?:e|es|ing)|fossil.fuel (?:question|language))\b`,
    terms: String.raw`climate (?:change|crisis|action|targets?|policy|litigation|adaptation|mitigation|resilience|risk|emergency|goals?|finance|summit|talks)|paris agreement|loss and damage|global (?:warming|heating|temperatures?)|greenhouse gas(?:es)?|carbon (?:emissions?|markets?|tax|credits?|capture|budget|border|sinks?)|net.zero|emissions (?:targets?|cuts?|trading|intensity)|methane|fossil.fuels?|coal ?mines?|coal (?:phase.?out|approvals?|power|plants?)|energy transition|just transition|ocean (?:heat|warming|acidification|temperatures?)|marine (?:heatwaves?|ecosystems?|life)|coral (?:reefs?|bleaching|loss)|sea.level rise|ice sheets?|glaciers?|glacial (?:melt|retreat)|permafrost|heat ?waves?|extreme (?:weather|heat|rainfall)|wildfires?|air (?:pollution|quality)|stubble burning|plastic (?:pollution|waste|ban|treaty)|single.use plastic|e.waste|solid waste|river pollution|groundwater (?:depletion|extraction|contamination)|water (?:crisis|scarcity|stress)|desertification|land degradation|sand mining|environmental (?:clearance|impact assessment|regulation|law|governance)|green (?:tribunal|credit|bonds?|cover)|tipping points?` },
  { id: 'physical-geography', subject: 'Geography', scope: 'knowledge', supports: ['evidence', 'explain', 'prescriptive', 'own'], acronyms: 'GLOF|ENSO|IST',
    support: String.raw`\b(?:onset|arrived|atypical|vulnerab\w+|preparedness|early warning|insufficient rainfall)\b`,
    terms: String.raw`el ni[ñn]o|la ni[ñn]a|indian ocean dipole|monsoons?|western disturbances?|cyclones?|cloudbursts?|landslides?|earthquakes?|seismic\w*|tsunamis?|volcan(?:o|oes|ic)|glacial lakes?|flash floods?|droughts?|jet streams?|ocean currents?|plate tectonics|river (?:systems?|basins?|linking|interlinking|erosion)|aquifers?|map projections?|flat map|time zones?|urbani[sz]ation|migration patterns?|patterns of migration|demographic (?:dividend|transition|change)|population (?:growth|decline|ageing|aging)|mineral (?:reserves?|deposits?|exploration)|lithium (?:reserves?|deposits?)|natural hazards?` },
  { id: 'heritage', subject: 'History & Culture', scope: 'domestic', supports: ['evidence', 'science', 'explain', 'law', 'own'], acronyms: 'ASI|UNESCO',
    support: String.raw`\b(?:unearth(?:s|ed)?|dates? back|legacy|inscribed|recogni[sz]ed|debated|restoration)\b`,
    terms: String.raw`archaeolog\w+|excavat\w+|inscriptions?|harappan?|indus valley|megalith\w*|keeladi|poompuhar|rakhigarhi|world heritage|intangible (?:cultural )?heritage|heritage (?:sites?|buildings?|conservation|tag)|classical language|gi tags?|geographical indication|temple architecture|buddhist (?:art|sites?|relics)|manuscripts?|constituent assembly|freedom (?:struggle|movement)|bhakti movement|chola|vijayanagara|mughal|mauryan?|tribal (?:art|culture|heritage|uprising)` },
]

/** Textual jurisdiction evidence. Publisher nationality and feed section never anchor an article. */
export const INDIA_ANCHOR_TERMS = String.raw`\b(?:India(?:n|ns)?|Bharat|Union (?:government|Cabinet|Minister|Budget)|central government|Lok Sabha|Rajya Sabha|New Delhi|Delhi|Finance Ministry|Home Ministry|Andhra Pradesh|Arunachal Pradesh|Assam|Bihar|Chhattisgarh|Goa|Gujarat|Haryana|Himachal(?: Pradesh)?|Jharkhand|Karnataka|Keralam?|Madhya Pradesh|Maharashtra|Manipur|Meghalaya|Mizoram|Nagaland|Odisha|Punjab|Rajasthan|Sikkim|Tamil Nadu|Telangana|Tripura|Uttar Pradesh|Uttarakhand|West Bengal|Jammu and Kashmir|Kashmir|Ladakh|Puducherry|Mumbai|Kolkata|Chennai|Bengaluru|Hyderabad|Constituent Assembly|Aadhaar|NITI Aayog|rupees?|fiscal federalism|Reserve Bank of India|Election Commission of India|Chief Justice of India)\b|₹`
export const INDIA_ANCHOR_ACRONYMS = String.raw`\b(?:Centre(?:[’']s)?|RBI|SEBI|ISRO|DRDO|GST|UPI|MHA|MEA|PMO|SC|HC|CJI|CEC|ECI|MeitY|IndiaAI|PDS|MGNREGA|NRIs?|IITs?|AIIMS|ICMR|UCC|NEP|CAG|NDMA|IMD|J&K|U\.P\.)\b(?!\/ST)`
export const domainTerms = (d: Domain) => String.raw`\b(?:${d.terms})\b`
export const domainAcronyms = (d: Domain) => d.acronyms ? String.raw`\b(?:${d.acronyms})\b` : null
export const domainSupport = (d: Domain) => join(...d.supports.filter(s => s !== 'own' && s !== 'explain').map(s => PROPOSITIONS[s as Exclude<Proposition, 'own'>]), ...(d.supports.includes('own') && d.support ? [d.support] : []))
