/** Finite contextual rules, not PYQ frequency or publisher scores. IDs are versioned. */
export const STAGE_C_POLICY = {
  id: 'tars-validator-stage-c/1', exam: 'UPSC', priorCap: 1,
  precedence: ['dominant_noise', 'party_primary', 'foreign_domestic', 'substantive_route', 'insufficient_metadata'],
  mustRead: 'explicit high-consequence mechanism; author/source cannot confer tier',
  scope: 'Global systemic developments require an explicit mechanism, never a World section or country alone',
} as const
export interface RouteRule { id: string; topic: string; support: string; scope: 'domestic' | 'knowledge' | 'systemic'; exceptional?: boolean }
// Both topic and substantive proposition must occur in the title or meaningful summary.
// Title-only rules deliberately require compound mechanisms rather than broad entities.
export const ROUTE_RULES: readonly RouteRule[] = [
  { id: 'C2.institution.v1', topic: String.raw`\b(supreme court|election commission|judicial independence|independent institutions|constitutional|electoral roll|anti-defection|fiscal federalism|finance commission)\b`, support: String.raw`\b(judgment|rul(?:e|es|ing)|invalidat\w*|approv\w*|changes?|independen\w*|mandate|equity|efficiency|reform\w*|federalism|trust|believe|legitimacy|autonomy|accountability|erosion)\b`, scope: 'knowledge', exceptional: true },
  { id: 'C2.electoral-rights.v1', topic: String.raw`\b(?:EC|election commission|electoral roll)\b`, support: String.raw`\b(mass deletions|voter rights|disenfranchis\w*|voting rights)\b`, scope: 'knowledge', exceptional: true },
  { id: 'C2.public-finance.v1', topic: String.raw`\b(capex strategy|fiscal policy|public debt|tax devolution|fiscal federalism|monetary policy|inflation transmission)\b`, support: String.raw`\b(how|why|measure|success|equity|efficiency|effects?|risks?|reforms?|transmission)\b`, scope: 'domestic', exceptional: true },
  { id: 'C2.distribution.v1', topic: String.raw`\b(inequality|economic mobility|middle.class|income distribution|labour market|labor market)\b`, support: String.raw`\b(redistribution|mobility|workers|salary|wages|income|poverty|squeezed|effects?|causes?)\b`, scope: 'domestic' },
  { id: 'C2.lending.v1', topic: String.raw`\b(lending transparency|loan rates|borrower protection|credit regulation)\b`, support: String.raw`\b(disclosures?|transparency|borrowers?|regulation|reforms?)\b`, scope: 'knowledge' },
  { id: 'C2.election-finance.v1', topic: String.raw`\b(election|electoral|campaign)\b.{0,50}\b(financ\w*|funding|spending|expen\w*)\b|\b(expen\w*|funding)\b.{0,30}\belection\b`, support: String.raw`\b(demographics|expenditure|disclosure|transparency|regulation|data|reform\w*)\b`, scope: 'domestic' },
  { id: 'C2.water-method.v1', topic: String.raw`\b(rivers?|wetlands?|watersheds?|groundwater)\b`, support: String.raw`\b(rejuvenation strategy|restoration methods?|conservation strategy|recharge mechanism|ecological restoration)\b`, scope: 'knowledge' },
  { id: 'C2.research.v1', topic: String.raw`\b(quantum computing|quantum research|optogenetics|gene editing|gravitational waves|ion channels|Nobel (?:Medicine|Physics|Chemistry)|fossil|dinosaur|exoplanet)\b`, support: String.raw`\b(new research|research (?:fields|discovers?|reveals?|finds?)|discover\w*|finding|found|identified|evidence|study (?:reveals?|finds?|shows?)|experiment|work on|mechanism)\b`, scope: 'knowledge' },
  { id: 'C2.climate-finding.v1', topic: String.raw`\b(climate change|global warming|biodiversity|ocean warming|carbon cycle)\b`, support: String.raw`\b(research (?:reveals?|finds?|shows?)|study (?:reveals?|finds?|shows?|warns?)|findings?|evidence|mechanism|tipping point|global treaty|global assessment)\b`, scope: 'knowledge' },
  { id: 'C2.energy-system.v1', topic: String.raw`\b(oil|crude|gas|energy)\b.{0,60}?\b(prices?|supply|stockpiles|flowing|markets?)\b`, support: String.raw`\b(Persian Gulf|Hormuz|global supply|world.{0,40}stockpiles|tensions.{0,30}Gulf|supply shock|inflation transmission)\b`, scope: 'systemic' },
  { id: 'C2.international-agreement.v1', topic: String.raw`\b(maritime security|trade agreement|arms control|global climate treaty)\b`, support: String.raw`\b(signs?|signed|treaty|agreement|obligations|adopts?|ratifies?)\b`, scope: 'systemic' },
  { id: 'C2.nuclear-security.v1', topic: String.raw`\b(nuclear enrichment|(?:Iran|uranium).{0,35}enrichment|nuclear arsenal|nuclear proliferation)\b`, support: String.raw`\b(war|treaty|non.proliferation|arms control|cuts?|limits?|safeguards)\b`, scope: 'systemic' },
  { id: 'C2.strategic-security.v1', topic: String.raw`\b(NATO|strategic exclave|Baltic exclave|maritime chokepoint|border security|defence readiness|defense readiness|cyber infrastructure|terror financ\w*)\b`, support: String.raw`\b(flashpoint|military|blockade|doctrine|capability|assessment|risks?|reform|treaty|security)\b`, scope: 'systemic' },
  { id: 'C2.world-order.v1', topic: String.raw`\b(multipolar world|great.power|diplomacy|US.Iran deal|international order|global governance|world trade|global debt)\b`, support: String.raw`\b(reality|test|wars?|climate change|Middle East|constraints?|reform\w*|consequences?|treaty|analysis|risks?)\b`, scope: 'systemic', exceptional: true },
  { id: 'C2.war-politics.v1', topic: String.raw`\b(?:Iran|Ukraine|Russia|Gaza)\b.{0,15}\bwar\b`, support: String.raw`\b(elections?.{0,30}(?:front|war)|peace deal|settlement|ceasefire|security|regional order)\b`, scope: 'systemic' },
  { id: 'C2.technology-governance.v1', topic: String.raw`\b(law enforcement|R&D ecosystem|research and development|AI governance|science policy|innovation system)\b`, support: String.raw`\b(AI|benefits|risks|knowledge.driven economy|regulation|reform|funding|ecosystem)\b`, scope: 'domestic', exceptional: true },
  { id: 'C2.national-capacity.v1', topic: String.raw`\b(MeitY|IndiaAI|national research|public health system)\b`, support: String.raw`\b(Centre of Excellence|capacity|regulation|reform|programme|program|initiative)\b`, scope: 'domestic' },
  { id: 'C2.regulatory-action.v1', topic: String.raw`\b(mining law|sports governance law|personality.rights|recruitment reform|data protection|banking regulation|competition law|environmental regulation)\b`, support: String.raw`\b(law|judgment|reform|regulat\w*|ruling|rights|states|federal|policy)\b`, scope: 'domestic', exceptional: true },
]
export const NOISE_RULES = [
  { code: 'C1.ceremonial_low_value.v1', pattern: String.raw`\b(memorial ceremony|memorial corridor|memorial (?:opening|ceremony)|garland\w*|courtesy visit|ceremonial visit|birthday tribute|foundation.stone ceremony)\b` },
  { code: 'C1.promotion.v1', pattern: String.raw`\b(buy now|discount code|sponsored post|product launch|promotional livestream|recruitment advertisement|apply now|coupon|campus award)\b` },
  { code: 'C1.entertainment.v1', pattern: String.raw`\b(live streaming|live telecast|match result|China Open exit|Princess Diana|royal family|celebrity gossip|box office|horoscope)\b` },
  { code: 'C1.roundup.v1', pattern: String.raw`\b(week in wildlife|best.{0,25}photographs|photo roundup|photo gallery)\b` },
  { code: 'C1.routine_business.v1', pattern: String.raw`\b(earnings season|quarterly earnings|stock tips|parking spaces.{0,30}flip|routine product recall)\b` },
  { code: 'C1.routine_local.v1', pattern: String.raw`\b(local outage|traffic diversion|isolated robbery|high school students.{0,15}protest|staff.{0,15}(?:dispute|politics)|personnel dispute)\b` },
] as const
export const PARTY_ACTORS = String.raw`\b(Congress|BJP|VCK|INDIA bloc|AfD|Farage|Bolsonaro|candidate|party|parties)\b`
export const PARTY_PURPOSE = String.raw`\b(demands?|slams?|attacks?|criticises?|campaign(?:ing|s)?|candidate strategy|campaign strategy|seat.sharing|alliance arithmetic|sit.in|detained|donations sting|boost|(?:favorite|favourite) to win|election could give|reign of terror|resignation)\b`
export const FOREIGN_DOMESTIC = String.raw`\b(France|French|Chinese|China|Brazil|Brazilian|America|American|U\.S\.|UK|British|Germany|German|Medicare|Republican|Democratic senators|Japan|Japanese|Canada|Canadian|Australia|Australian|Italy|Spain|Russia|Russian|Ukraine|Ukrainian|Korea|Korean|Mexico|Israel|Israeli|Iran|Iranian|Iraq|Syria|Turkey|Egypt|Egyptian|Saudi|UAE|Qatar|Nigeria|Kenya|Sudan|Indonesia|Vietnam|Philippines|Singapore|Thailand|Argentina|Switzerland|Swiss|Denmark|Finland)\b`
export const DOMESTIC_PURPOSE = String.raw`\b(high school|parking spaces|Medicare|Social Security|energy permitting|federal energy|supreme court|local court|domestic court|local climate lawsuit|climate lawsuit|domestic legislation|local election|presidency|staff dispute|personnel)\b`
