/** Generated by tools/news/build-validator-manifest.ts; never edit by hand. */
export const RUNTIME_VERSIONS = {
  "policyId": "tars-validator-stage-c/1",
  "policyHash": "1d27281bacd3b6e3c6c45c388b350c2fe99953fd561867a8818f5a998043e496",
  "indexHash": "2c2f551660477a40f5c22bf94c543259e057be33d5966d210fc24c23c407b348",
  "registryHash": "de31011cab4b5ca22e130016aaaecd5d41e867ea7bea0a21b101dc9ba9bc9d21",
  "authorHash": "431a9da8003ae1566091cb698b45304a8079026e78162c6c4f1c610803f69900",
  "codeHash": "bbe9e2b6467ea40380273122dba2fe835aae6c2bb7d4e23104620c65938d36e2"
} as const
