/** Generated by tools/news/build-validator-manifest.ts; never edit by hand. */
export const RUNTIME_VERSIONS = {
  "policyId": "tars-validator-stage-c/1",
  "policyHash": "3101eab54f2c6b12590955bc0b8dc7203e4fa0bcfd938fdf46a4b78f1ac6ec06",
  "indexHash": "2c2f551660477a40f5c22bf94c543259e057be33d5966d210fc24c23c407b348",
  "registryHash": "de31011cab4b5ca22e130016aaaecd5d41e867ea7bea0a21b101dc9ba9bc9d21",
  "authorHash": "431a9da8003ae1566091cb698b45304a8079026e78162c6c4f1c610803f69900",
  "codeHash": "31fe9f71fde092b942833ed02b1e0e41fb45e3fb365bb47e070e4614246119dc"
} as const
