/** Generated by tools/news/build-validator-manifest.ts; never edit by hand. */
export const RUNTIME_VERSIONS = {
  "policyId": "tars-validator-stage-c/1",
  "policyHash": "d941862b83d8dc26a544c5881fadda31b9cb9f1703b93d0152a74f7a8d6cfcf4",
  "indexHash": "2c2f551660477a40f5c22bf94c543259e057be33d5966d210fc24c23c407b348",
  "registryHash": "de31011cab4b5ca22e130016aaaecd5d41e867ea7bea0a21b101dc9ba9bc9d21",
  "authorHash": "431a9da8003ae1566091cb698b45304a8079026e78162c6c4f1c610803f69900",
  "codeHash": "4f61a4aa7bfc53b2df51fe08b09d547f8f244729cff3118749356dd87348b0fb"
} as const
