/**
 * Editorial evidence vocabulary for the News validator: how an article is framed, where it is set, and what makes
 * it noise. These are phrase tables read by one matcher, never exam claims; PYQ-backed concepts live in the index.
 * A leading ^ matches case-sensitively.
 */
const list = (text: string) => text.split(';').map(s => s.trim()).filter(Boolean)

/** How the development is framed. One category counts once, more in the headline than in the summary. */
export const FRAMING: { id: string; label: string; terms: string[] }[] = [
  { id: 'law', label: 'Law or policy action', terms: list('bill; ^Act; ordinance; amendment; amendments; notifies; notified; notification; draft rules; draft policy; draft bill; guidelines; framework; policy; scheme; mission; norms; rules; regulations; reform; reforms; cabinet approves; cabinet clears; cabinet nod; approves; approval; clearance; rolls out; rollout; to implement; implementation; mandates; mandatory; bans; ban on; ban; curbs; restrictions; lifts ban; withdraws; scraps; scrap; repeal; repeals; extends; raises; hikes; cuts; revises; revised; overhaul; decriminalise; decriminalisation; subsidy; incentive; incentives; tender; auction; allocation; allocates; outlay; target; targets; roadmap; action plan; task force; panel; committee; commission; advisory; directive; moratorium; cap; ceiling; exemption; exempt; quota') },
  { id: 'court', label: 'Substantive court or tribunal decision', terms: list('verdict; ruling; rules; judgment; judgement; strikes down; struck down; upholds; upheld; quashes; quashed; sets aside; directs; directed; orders; ordered; stays; stayed; constitution bench; landmark; declares; holds that; reserves verdict; refers to larger bench; suo motu; takes cognisance; takes up; pulls up; raps; questions centre; asks centre; notice to centre; under what law; unconstitutional; violates') },
  { id: 'data', label: 'Official data, report or study', terms: list('report; reports; index; survey; data; study; studies; research; researchers; scientists; estimates; estimate; forecast; projection; projections; outlook; ranking; rankings; census; audit; white paper; assessment; findings; analysis; review; statistics; per cent; percent; rises to; falls to; grows; growth; record high; record low; all time high; all time low; highest; lowest; decade; lakh crore; billion; trillion') },
  { id: 'diplomacy', label: 'Diplomatic or strategic development', terms: list('summit; talks; visit; visits; agreement; pact; treaty; deal; MoU; joint statement; dialogue; sanctions; negotiations; negotiation; bilateral; trilateral; multilateral; envoy; envoys; ambassador; foreign minister; summons; summon; ties; relations; partnership; cooperation; alliance; proposal; resolution; vote; veto; ceasefire; truce; blockade; withdraws from; joins; membership; presidency; chair; hosts; mediation; back channel') },
  { id: 'launch', label: 'Mission, discovery or deployment', terms: list('launch; launches; launched; mission; discovery; discovered; discovers; discover; breakthrough; develops; developed; indigenous; first ever; India\'s first; world\'s first; unveils; tested; test fired; successfully; commissioned; inducted; deploys; deployment; prototype; trial; trials; pilot project; field trial; reintroduction; released into; translocated; declared; designated; recognised; tag; inscribed') },
  { id: 'explain', label: 'Explanatory framing', terms: list('explained; explainer; what is; what are; what it means; why it matters; what we know; how it works; decoded; in depth; deep dive; a primer; key takeaways; takeaways; lessons; implications; challenges; way forward; the case for; the case against; why; how; expert explains') },
]

/** Explicit India anchoring in the text. Indian papers' national sections are treated as India-set without it. */
export const INDIA = list('India; Indian; Indians; Bharat; ^Centre; Union government; central government; Government of India; ^GoI; Union Cabinet; Union Minister; Union Budget; Lok Sabha; Rajya Sabha; New Delhi; Delhi; Modi; PM Modi; Prime Minister Modi; Sitharaman; Jaishankar; Amit Shah; Rajnath; Goyal; Vaishnaw; Murmu; ^MHA; ^MEA; ^PMO; Finance Ministry; Home Ministry; Commerce Ministry; ^Govt; rupee; lakh; crore; Andhra Pradesh; Arunachal Pradesh; Assam; Bihar; Chhattisgarh; Goa; Gujarat; Haryana; Himachal Pradesh; Himachal; Jharkhand; Karnataka; Kerala; Keralam; Madhya Pradesh; Maharashtra; Manipur; Meghalaya; Mizoram; Nagaland; Odisha; Punjab; Rajasthan; Sikkim; Tamil Nadu; Telangana; Tripura; Uttar Pradesh; Uttarakhand; West Bengal; Bengal; Jammu and Kashmir; Kashmir; Ladakh; Puducherry; Chandigarh; Andaman; Lakshadweep; Mumbai; Kolkata; Chennai; Bengaluru; Hyderabad; Ahmedabad; Pune; Jaipur; Patna; Bhopal; Guwahati; Srinagar; Thiruvananthapuram; Northeast; North East; ^NCR; ^RBI; ^SEBI; ^ISRO; ^DRDO; NITI Aayog; ^GST; ^UPI; Aadhaar; ^BJP; Congress party; ^AAP; ^DMK; ^TMC; ^IAF; Air Chief; Army Chief; Navy Chief; ^ED; ^CBI; ^NIA; ^SC; ^HC; ^EC; ^CEC; ^CJI; ^FM; ^CM; ^UP; U P; ^MP; ^TN; ^AP; J K; ^NGT; ^NHRC; ^FSSAI; ^IMD; ^NITI; ^MSP; ^PDS; ^IIT; ^IITs; ^AIIMS; Yogi; Sitharaman; state government; state govt; Haryana govt; Vidhan Sabha; gram sabha; panchayat')

/** Places and actors that set a story abroad. With no India anchor, domestic-institution matches are discounted. */
export const ABROAD = list('^US; U S; American; Americans; America; Trump; White House; Washington; Texas; Florida; California; Louisiana; Alabama; New York; Tennessee; Britain; British; ^UK; England; London; Scotland; Wales; Tory; Tories; Labour party; Reform UK; Starmer; Heathrow; Devon; Europe; European; Germany; German; France; French; Paris; Italy; Spain; Russia; Russian; Putin; Ukraine; Ukrainian; China; Chinese; Beijing; Japan; Japanese; Tokyo; Korea; Korean; Australia; Australian; Canada; Canadian; Brazil; Brazilian; Mexico; Israel; Israeli; Iran; Iranian; Iraq; Syria; Turkey; Egypt; Egyptian; Saudi; Dubai; ^UAE; Qatar; Africa; African; Nigeria; Kenya; Sudan; Indonesia; Vietnam; Philippines; Singapore; Thailand; Argentina; Switzerland; Swiss; Denmark; Finland; Siberia')

/** Names that set a story in the United States. */
export const UNITED_STATES = list('^US; U S; American; Americans; America; Trump; Biden; Vance; White House; Washington; Pentagon; Capitol Hill; Texas; Florida; California; Louisiana; Alabama; New York; ^NYC; Tennessee; Colorado; Georgia; Ohio; Michigan; Virginia; Massachusetts; Arizona; Nevada; Pennsylvania; Illinois; Chicago; Los Angeles; Silicon Valley; Wall Street')
/**
 * Marks of American domestic affairs: its courts, Congress, parties, states, policing and campus life. A US story with
 * one of these and no India or international dimension is not UPSC current affairs, whatever concept it mentions.
 */
export const US_DOMESTIC = list('White House; Trump administration; administration; federal; Congress; Senate; Senator; House Republicans; Republican; Republicans; Democrat; Democrats; ^GOP; midterm; midterms; Supreme Court; judge; judges; justices; Justice Department; ^DOJ; ^FBI; ^ICE; governor; county; city council; state law; lawsuit; sue; sues; sued; czar; task force; names; nominee; nominates; appoints; Americans; voters; ^NYC; New York; California; Texas; Florida; Colorado; Alabama; Louisiana; Tennessee; Georgia; Ohio; Michigan; Virginia; Massachusetts; Arizona; Nevada; Pennsylvania; Illinois; Chicago; Los Angeles; hearing; testify; testifies; school; schools; students; college; campus; police; sheriff; immigrant; immigrants; deported; deportation; heating bills; bills; consumers; consumer; shoppers; homeowners; rename; executive order')

export interface NoiseCategory { id: string; label: string; points: number; hard?: boolean; terms: string[] }
/**
 * Noise evidence, read from the headline. Hard categories are never current affairs and reject outright; the rest
 * subtract, so a substantive article that happens to mention a crime or a market move can still qualify.
 */
export const NOISE: NoiseCategory[] = [
  { id: 'exam-practice', label: 'Quiz, practice or exam administration', points: 0, hard: true, terms: list('quiz; MCQ; MCQs; mock test; answer practice; answer writing; admit card; answer key; cut off marks; result declared; results declared; recruitment; vacancies; apply online; application form; Jobs 2026; Career 2026; hall ticket; exam date; crossword; Wordle; sudoku') },
  { id: 'astrology', label: 'Horoscope or lottery', points: 0, hard: true, terms: list('horoscope; zodiac; astrology; numerology; panchang; lucky day; lottery; tarot; rashifal') },
  { id: 'sports', label: 'Sports result or fixture', points: 0, hard: true, terms: list('cricket; ^IPL; T20; ^ODI; Test match; wicket; wickets; innings; football; ^FIFA; Premier League; Champions League; La Liga; tennis; Grand Slam; Wimbledon; ^NBA; ^NFL; Formula 1; ^F1; Grand Prix; badminton; hockey; kabaddi; wrestling; boxing; golf; match score; live score; scorecard; goal scorer; hat trick; medal tally; Asian Games; Asiad; Olympics; Olympic; Commonwealth Games; World Cup; Ronaldo; Messi; Kohli; Dhoni; Chess960; grandmaster; playing XI') },
  { id: 'entertainment', label: 'Celebrity or entertainment', points: 0, hard: true, terms: list('box office; film release; movie release; movie; trailer; teaser; Bollywood; Hollywood; Tollywood; celebrity; celebrities; actress; web series; ^OTT; Netflix; Bigg Boss; reality show; singer; rapper; album; concert; red carpet; Met Gala; runway; gets engaged; engaged to; wedding; girlfriend; boyfriend; dating; divorce; baby bump; net worth; fashion week; beauty pageant; Miss Universe; Miss World') },
  { id: 'gadgets', label: 'Consumer product or gadget', points: 0, hard: true, terms: list('smartphone; smartphones; iPhone; Samsung Galaxy; Google Pixel; earbuds; smartwatch; laptop review; tablet review; price in India; specs; launch offer; best deals; Amazon sale; Flipkart sale; discount offer; Windows PC; gaming console; PlayStation; Xbox; unboxing') },
  { id: 'press-release', label: 'Press release or sponsored content', points: 0, hard: true, terms: list('PRNewswire; Business Wire; BusinessWire; ^ANI Press Release; sponsored; partner content; brand connect; brand post; advertorial') },
  { id: 'markets', label: 'Market movement or stock tip', points: -5, terms: list('gains as; slips as; falls as; rises as; futures; ^IPOs; Sensex; Nifty; stock market; stock markets; stocks to; stock price; share price; shares rise; shares fall; shares jump; shares surge; shares slump; shares tumble; stocks rise; stocks fall; stocks jump; stocks surge; stock split; share split; multibagger; target price; buy or sell; Nikkei; Dow Jones; Nasdaq; Wall Street; ^IPO; quarterly results; Q1 results; Q2 results; Q3 results; Q4 results; net profit; market cap; gold price; gold slips; gold rate; silver price; bullion; rally; rebound; dividend; opening bell; closing bell; early trade; weekly decline') },
  { id: 'crime', label: 'Routine crime or police report', points: -4, terms: list('murder; murdered; hacked to death; rape; raped; gang rape; robbery; loot; arrested; arrest; shot dead; stabbed; stabbing; kidnapped; kidnapping; found dead; suicide; molestation; accused; charged with; charged over; chargesheet; ^FIR; custody; remand; bail; bail plea; anticipatory bail; lethal injection; accomplice; shooting; gunman; assault; brawl; scam accused; insurance claims; honour killing; heist') },
  { id: 'accident', label: 'Accident or casualty report', points: -2.5, terms: list('road accident; bus hits; truck hits; car crash; plane crash; crash; crashes; collision; drown; drowns; drowned; washed away; injured; dies; dead; killed; death toll; stampede; fire breaks out; blaze; derails; capsizes; debris; missing jet') },
  { id: 'court-routine', label: 'Routine court procedure', points: -2, terms: list('dismisses plea; rejects plea; junks plea; adjourns; adjourned; defers hearing; to hear; agrees to hear; agrees to list; listed for; seeks response; move HC; move High Court; bail plea; refuses to entertain; withdraws plea') },
  { id: 'politics', label: 'Party politics or campaign', points: -3.5, terms: list('^BJP; Congress leader; Congress leaders; Youth Congress; ^NSUI; ^AAP; ^TMC; ^DMK; ^TVK; Kharge; Rahul Gandhi; Thackeray; Akhilesh; Mamata; Kejriwal; demands answers; threatens agitation; ouster; non negotiable; ^polls; ^Polls; poll strategy; likely picks; picks; nominees; caste reset; steps up preparations; Elections 2027; Election 2027; assembly polls; accuses; lashes out; rip apart; takes potshots; mocks; claims anger; joins BJP; joins Congress; joins TMC; joins AAP; roadshow; slams; hits out; takes a dig; jibe; war of words; heckled; bypoll; seat sharing; star campaigner; outreach; vote bank; defecting; defection; poll campaign; campaign trail; nail biting; high stakes; eyes comeback; seeks repeat; battle for; versus; ^vs; INDIA bloc; alliance talks; expelled; factional; infighting; snub; row erupts') },
  { id: 'soft', label: 'Human-interest or lifestyle feature', points: -3.5, terms: list('^Meet; ^Watch; Bollywood actor; film actor; Meet the; Who is; Who was; goes viral; viral; internet reacts; netizens; love story; birthday; inspiring; heartwarming; video shows; in pics; photos; photo; photography; exhibition; recipe; fashion; saree; weight loss; diet; skincare; fitness; yoga poses; relationship; home loan; ^EMI; credit card; mutual fund; mutual funds; ^SIP; tax saving tips; how to save; seventh grader; eighth grader; paperweight; miniature; bravery; courage; hailed; dazzles; outshines; doomscrollers; diarrhea; bacon') },
  { id: 'digest', label: 'Digest, roundup or live blog', points: -5, terms: list('World Live; News Highlights; live results; war live; video; podcast; newsletter; Rush Hour; top news; live updates; ^LIVE; Recommendations for the week; Science Snapshots; week in wildlife; The week in; weather tracker; daily weather; Starwatch; Country diary; cartoon; Green Humour; letters to the editor; morning brief; evening brief; weekly policy watch; top 20; pointers of the past week; news in numbers; at a glance; documentary') },
  { id: 'weather', label: 'Routine weather bulletin', points: -3.5, terms: list('weather tracker; daily weather; weather update; weather department predicts; predicts heavy rain; heavy rain; heavy rains; rain alert; yellow alert; orange alert; red alert; respite likely; showers; thunderstorm; thunderstorms; temperature dips; mercury dips; fog') },
  { id: 'routine', label: 'Ceremonial or routine engagement', points: -2.5, terms: list('meets; calls on; courtesy call; holds bilateral meetings; pays tribute; pays homage; greets; extends greetings; condoles; inaugurates; flags off; lays foundation stone; felicitates; distributes; attends; addresses rally; hails; lauds; praises') },
  { id: 'corporate', label: 'Company announcement', points: -3, terms: list('world record; world records; prestigious; honoured; fuel surcharge; expands beyond; rename; renames; rebrand; rebrands; ^CEO; ^MD; re elected as; elected president of; secures contract; bags order; wins order; debuts; expands in; plans to expand; signs MoU with; partners with; ties up with; acquires; fundraise; raises funding; funding round; valuation; Ltd; hiring; hires; white collar; airfares; fuel charges; fuel charge; fare hike') },
]

/** Small priors from the feed an item arrived in. None reaches the acceptance threshold on its own. */
export function sourcePrior(sourceId: string | undefined, section: string): { points: number; label: string } | null {
  if (sourceId === 'ie-upsc') return { points: 4, label: 'Publisher-curated UPSC section' }
  if (/explained|explainer/i.test(section)) return { points: 2, label: 'Explainer section' }
  if (/editorial|opinion/i.test(section)) return { points: 1, label: 'Editorial or opinion section' }
  if (sourceId === 'et-uttarpradesh') return { points: 1, label: 'Uttar Pradesh state feed' }
  if (/^(?:economy|governance|environment|science|agriculture|climate|finance & economics|environment & development|science & environment)/i.test(section)) return { points: 1, label: `${section} section` }
  if (/^markets$/i.test(section)) return { points: -1, label: 'Markets feed' }
  return null
}
