/** Local deterministic code/policy commitments. No network or dataset mutation. */
import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { NEWS_SOURCES } from '../../src/current-affairs/sources.ts'
import { STAGE_C_POLICY } from '../../src/current-affairs/validator-v3/policy.ts'
const hash = (path: string) => createHash('sha256').update(readFileSync(path)).digest('hex')
function stable(value: unknown): string {
  if (Array.isArray(value)) return '[' + value.map(stable).join(',') + ']'
  if (value && typeof value === 'object') return '{' + Object.entries(value).sort(([a], [b]) => a.localeCompare(b, 'en')).map(([k, v]) => JSON.stringify(k) + ':' + stable(v)).join(',') + '}'
  return JSON.stringify(value)
}
const digest = (v: unknown) => createHash('sha256').update(stable(v)).digest('hex')
const root = 'src/current-affairs/validator-v3/'
const files = readdirSync(root).filter(n => n.endsWith('.ts') && !n.endsWith('.test.ts') && n !== 'runtime-manifest.ts').map(n => root + n)
files.push('src/features/current-affairs/useNewsModel.ts', 'src/features/current-affairs/useValidatorSelection.ts', 'src/features/current-affairs/usePersonalState.ts', 'src/features/current-affairs/NewsScreen.tsx', 'src/current-affairs/workspace.ts', 'src/current-affairs/analytics.ts', 'src/current-affairs/topics.ts', 'src/current-affairs/types.ts', 'src/current-affairs/reader/policy.ts')
const inventory = files.sort().map(path => ({ path, sha256: hash(path) }))
const versions = { policyId: STAGE_C_POLICY.id, policyHash: hash(root + 'policy.ts'), indexHash: hash('public/current-affairs/v2/relevance-index.json'), registryHash: digest(NEWS_SOURCES), authorHash: hash(root + 'author-registry.ts'), codeHash: digest(inventory) }
writeFileSync(root + 'runtime-manifest.ts', '/** Generated by tools/news/build-validator-manifest.ts; never edit by hand. */\nexport const RUNTIME_VERSIONS = ' + JSON.stringify(versions, null, 2) + ' as const\n')
writeFileSync(process.env.VALIDATOR_INVENTORY_PATH ?? 'docs/release/runtime-inventory.json', JSON.stringify({ versions, inventory }, null, 2) + '\n')
console.log('Validator manifest: ' + inventory.length + ' local code files committed by hash')
